import type { SousCategorie } from '@alambic/noyau'

// Les produits, pas les enseignes. La table soeur (mots-cles-categories) reconnait chez qui on
// a paye ; celle-ci reconnait ce qu'on a mis dans le panier, ligne d'article par ligne
// d'article.
//
// Un libelle d'article ne dit jamais la nature du commerce a lui seul — « biere » se vend en
// epicerie comme a la brasserie, « banane » se retrouve dans une boite a lunch de restaurant.
// C'est le panier entier qui tranche : banane + biere + pain, c'est une epicerie. Cette table
// ne fournit donc que les indices ; le poids et le vote appartiennent au reconnaisseur.
//
// Format identique a la table soeur : deja normalise — minuscules, sans accents, espaces
// simples, singulier quand le pluriel se devine (le reconnaisseur compare des fenetres de
// mots, « bananes » ne matchera pas « banane », d'ou les pluriels courants ecrits en clair).
// L'anglais figure a cote du francais : les caisses quebecoises impriment les deux.
//
// Le Record force l'exhaustivite comme dans la table soeur : une sous-categorie ajoutee au
// noyau casse la compilation ici tant qu'elle n'a pas sa liste, fut-elle vide. Une liste vide
// dit qu'aucun produit ne se lit sur un ticket pour cette depense (un loyer n'a pas
// d'articles).
export const MOTS_CLES_PRODUITS: Record<SousCategorie, readonly string[]> = {
  loyer: [],
  hypotheque: [],
  'assurance-habitation': [],
  electricite: [],
  chauffage: ['buche', 'buches', 'granule', 'granules', 'allume feu', 'bonbonne propane'],
  'entretien-maison': [
    'vis',
    'clou',
    'clous',
    'boulon',
    'ecrou',
    'cheville',
    'ancrage',
    'marteau',
    'tournevis',
    'perceuse',
    'meche',
    'scie',
    'lame de scie',
    'ruban a mesurer',
    'niveau',
    'pince',
    'cle a molette',
    'echelle',
    'escabeau',
    'etabli',
    'ponceuse',
    'papier sable',
    'peinture',
    'peinture latex',
    'apprete',
    'primer',
    'vernis',
    'teinture',
    'pinceau',
    'rouleau a peinture',
    'ruban a peintre',
    'toile de peintre',
    'calfeutrant',
    'silicone',
    'scellant',
    'colle',
    'colle a bois',
    'epoxy',
    'ruban adhesif',
    'duct tape',
    'ruban electrique',
    'plywood',
    'contreplaque',
    'gypse',
    'placoplatre',
    'compose a joints',
    'ciment',
    'mortier',
    'beton',
    'sable',
    'gravier',
    'brique',
    'bloc de beton',
    'planche',
    'madrier',
    'deux par quatre',
    '2x4',
    'moulure',
    'plinthe',
    'lambris',
    'isolant',
    'laine minerale',
    'pare vapeur',
    'bardeau',
    'membrane',
    'gouttiere',
    'solin',
    'tuile',
    'ceramique',
    'coulis',
    'plancher flottant',
    'sous plancher',
    'robinet',
    'lavabo',
    'toilette',
    'siege de toilette',
    'douchette',
    'pomme de douche',
    'tuyau',
    'pvc',
    'raccord',
    'coude',
    'valve',
    'chauffe eau',
    'drain',
    'debouche drain',
    'fil electrique',
    'cable electrique',
    'prise',
    'interrupteur',
    'disjoncteur',
    'boite electrique',
    'ampoule',
    'ampoule del',
    'tube fluorescent',
    'luminaire',
    'ventilateur de salle de bain',
    'detecteur de fumee',
    'thermostat',
    'filtre a fournaise',
    'serrure',
    'poignee de porte',
    'cadenas',
    'charniere',
    'penture',
    'moustiquaire',
    'coupe froid',
    'pelle a neige',
    'gratte',
    'sel de deglacage',
    'abrasif',
    'tondeuse a gazon',
    'coupe bordure',
    'souffleuse',
    'taille haie',
    'semence a gazon',
    'engrais',
    'terre a jardin',
    'terreau',
    'paillis',
    'tourbe',
    'boyau d arrosage',
    'arrosoir',
    'rateau',
    'secateur',
    'gants de travail',
    'lunettes de securite',
    'masque n95',
    'bache',
    'corde',
    'chaine',
    'attache',
    'tie wrap',
    'batterie 9v',
    'chlore',
    'chlore piscine',
    'pastilles de chlore',
    'ampoule led',
    'prise usb murale',
    'gradateur',
    'boite a fusibles',
    'rallonge electrique',
    'multiprise',
    'minuterie',
    'detecteur de monoxyde',
    'extincteur',
    'isolant en mousse',
    'scellant a fenetre',
    'moustiquaire de porte',
    'seuil de porte',
    'poignee d armoire',
    'tiroir coulissant',
    'tablette murale',
    'support mural',
    'ancrage mural',
    'vis a gypse',
    'vis a bois',
    'vis a terrasse',
    'clou de finition',
    'cloueuse',
    'compresseur',
    'generatrice',
    'aspirateur d atelier',
    'chariot',
    'brouette',
    'pelle',
    'beche',
    'houe',
    'sarcloir',
    'tuteur',
    'treillis',
    'semences',
    'bulbes',
    'vivaces',
    'annuelles',
    'arbuste',
    'arbre fruitier',
    'terre noire',
    'compost',
    'chaux',
    'pesticide',
    'herbicide',
    'sel a piscine',
    'produits de piscine',
    'toile solaire',
    'filtre de piscine',
    'pompe de piscine',
    'spa produits',
    'bandelettes d analyse',
  ],
  'meubles-deco': [
    'table',
    'table de cuisine',
    'table de chevet',
    'table basse',
    'chaise',
    'tabouret',
    'banc',
    'fauteuil',
    'sofa',
    'divan',
    'canape',
    'causeuse',
    'pouf',
    'lit',
    'sommier',
    'matelas',
    'base de lit',
    'tete de lit',
    'commode',
    'armoire',
    'garde robe',
    'penderie',
    'etagere',
    'bibliotheque',
    'buffet',
    'meuble tv',
    'bureau',
    'classeur',
    'miroir',
    'cadre',
    'toile decorative',
    'affiche',
    'horloge murale',
    'vase',
    'chandelier',
    'bougie',
    'bougie parfumee',
    'diffuseur',
    'plante artificielle',
    'pot de fleurs',
    'cache pot',
    'rideau',
    'tringle a rideau',
    'store',
    'toile de store',
    'coussin',
    'housse de coussin',
    'jete',
    'couverture',
    'douillette',
    'couette',
    'housse de couette',
    'drap',
    'drap contour',
    'taie d oreiller',
    'oreiller',
    'protege matelas',
    'tapis',
    'carpette',
    'paillasson',
    'serviette de bain',
    'debarbouillette',
    'rideau de douche',
    'panier a linge',
    'poubelle',
    'corbeille',
    'bac de rangement',
    'boite de rangement',
    'panier de rangement',
    'crochet mural',
    'patere',
    'lampe',
    'lampe de table',
    'lampe sur pied',
    'abat jour',
    'guirlande lumineuse',
    'vaisselle',
    'assiette',
    'bol',
    'verre',
    'coupe a vin',
    'tasse',
    'mug',
    'ustensile',
    'couteau de cuisine',
    'planche a decouper',
    'chaudron',
    'casserole',
    'poele',
    'plat de cuisson',
    'moule a gateau',
    'grille pain',
    'bouilloire',
    'cafetiere',
    'melangeur',
    'robot culinaire',
    'micro ondes',
    'friteuse a air',
    'mijoteuse',
    'aspirateur',
    'balai',
    'vadrouille',
    'seau',
    'planche a repasser',
    'fer a repasser',
    'chaise de bureau',
    'chaise pliante',
    'table pliante',
    'table d appoint',
    'table de salle a manger',
    'ensemble de cuisine',
    'banc de rangement',
    'console d entree',
    'meuble a chaussures',
    'support a manteau',
    'cadre photo',
    'toile murale',
    'papier peint',
    'decalque mural',
    'tapis de salon',
    'tapis de couloir',
    'rideaux occultants',
    'voilage',
    'store venitien',
    'store cellulaire',
    'housse de sofa',
    'jete de laine',
    'couvre lit',
    'cache sommier',
    'ensemble de draps',
    'oreiller memoire',
    'protege oreiller',
    'serviettes ensemble',
    'tapis de bain',
    'poubelle de salle de bain',
    'distributeur a savon',
    'porte serviette',
    'organisateur de tiroir',
    'bacs empilables',
    'etagere murale',
    'support tv',
    'table de nuit',
    'lampe de chevet',
    'veilleuse',
    'bougeoir',
    'vase decoratif',
    'plante verte',
    'succulente',
    'arbre de noel',
    'decorations de noel',
    'guirlande',
    'ensemble de vaisselle',
    'batterie de cuisine',
    'couteaux ensemble',
    'bols a melanger',
    'passoire',
    'spatule',
    'fouet',
    'louche',
    'rape',
    'moulin a poivre',
    'contenants hermetiques',
    'boite a lunch',
    'thermos',
    'cafetiere filtre',
    'machine espresso',
    'grille pain 4 tranches',
    'batteur',
    'balance de cuisine',
  ],
  internet: [],
  cellulaire: ['etui de telephone', 'protecteur d ecran', 'chargeur', 'cable usb', 'ecouteurs'],
  epicerie: [
    'pomme',
    'pommes',
    'banane',
    'bananes',
    'orange',
    'oranges',
    'clementine',
    'clementines',
    'mandarine',
    'citron',
    'lime',
    'pamplemousse',
    'raisin',
    'raisins',
    'raisins verts',
    'raisins rouges',
    'fraise',
    'fraises',
    'framboise',
    'framboises',
    'bleuet',
    'bleuets',
    'mure',
    'mures',
    'canneberge',
    'canneberges',
    'cerise',
    'cerises',
    'peche',
    'peches',
    'poire',
    'poires',
    'prune',
    'prunes',
    'abricot',
    'nectarine',
    'melon',
    'melon d eau',
    'cantaloup',
    'melon miel',
    'ananas',
    'mangue',
    'papaye',
    'kiwi',
    'avocat',
    'avocats',
    'grenade',
    'figue',
    'datte',
    'dattes',
    'noix de coco',
    'rhubarbe',
    'fruits',
    'fruit',
    'salade de fruits',
    'apple',
    'banana',
    'grapes',
    'strawberry',
    'blueberry',
    'lemon',
    'avocado',
    'legume',
    'legumes',
    'patate',
    'patates',
    'pomme de terre',
    'pommes de terre',
    'patate douce',
    'carotte',
    'carottes',
    'oignon',
    'oignons',
    'oignon vert',
    'echalote',
    'ail',
    'gousse d ail',
    'celeri',
    'brocoli',
    'chou fleur',
    'chou',
    'chou rouge',
    'chou de bruxelles',
    'chou frise',
    'kale',
    'laitue',
    'laitue romaine',
    'laitue iceberg',
    'salade',
    'melange de salade',
    'epinard',
    'epinards',
    'roquette',
    'concombre',
    'concombres',
    'tomate',
    'tomates',
    'tomates cerises',
    'tomates raisins',
    'poivron',
    'poivrons',
    'poivron rouge',
    'poivron vert',
    'piment',
    'jalapeno',
    'courgette',
    'zucchini',
    'aubergine',
    'courge',
    'citrouille',
    'navet',
    'rutabaga',
    'betterave',
    'radis',
    'panais',
    'poireau',
    'asperge',
    'asperges',
    'haricot',
    'haricots verts',
    'feve',
    'pois',
    'pois mange tout',
    'mais',
    'epi de mais',
    'champignon',
    'champignons',
    'gingembre',
    'herbes',
    'persil',
    'coriandre',
    'basilic',
    'ciboulette',
    'menthe',
    'thym',
    'romarin',
    'potato',
    'onion',
    'carrot',
    'lettuce',
    'tomato',
    'cucumber',
    'broccoli',
    'mushroom',
    'viande',
    'boeuf',
    'boeuf hache',
    'boeuf hache mi maigre',
    'steak',
    'bifteck',
    'roti',
    'roti de porc',
    'roti de boeuf',
    'contre filet',
    'faux filet',
    'filet mignon',
    'bavette',
    'palette',
    'cubes a ragout',
    'porc',
    'porc hache',
    'cotelette',
    'cotelette de porc',
    'cotes levees',
    'longe de porc',
    'jambon',
    'bacon',
    'saucisse',
    'saucisses',
    'saucisse italienne',
    'saucisse a hot dog',
    'merguez',
    'veau',
    'agneau',
    'poulet',
    'poitrine de poulet',
    'haut de cuisse',
    'cuisse de poulet',
    'pilon',
    'aile de poulet',
    'ailes de poulet',
    'poulet hache',
    'poulet entier',
    'poulet roti',
    'dinde',
    'dinde hachee',
    'canard',
    'jambon fume',
    'charcuterie',
    'salami',
    'pepperoni',
    'prosciutto',
    'viande fumee',
    'cretons',
    'pate',
    'poisson',
    'saumon',
    'filet de saumon',
    'saumon fume',
    'truite',
    'tilapia',
    'morue',
    'sole',
    'aiglefin',
    'thon',
    'thon en conserve',
    'sardine',
    'sardines',
    'crevette',
    'crevettes',
    'crabe',
    'homard',
    'moules',
    'petoncle',
    'petoncles',
    'calmar',
    'tofu',
    'tempeh',
    'proteine vegetale',
    'beef',
    'chicken',
    'pork',
    'ground beef',
    'turkey',
    'salmon',
    'shrimp',
    'ham',
    'lait',
    'lait 2',
    'lait 3 25',
    'lait ecreme',
    'lait au chocolat',
    'lait d amande',
    'lait de soya',
    'lait d avoine',
    'boisson vegetale',
    'creme',
    'creme 15',
    'creme 35',
    'creme a fouetter',
    'creme sure',
    'creme glacee',
    'yogourt',
    'yogourt grec',
    'yaourt',
    'kefir',
    'fromage',
    'fromage rape',
    'cheddar',
    'mozzarella',
    'parmesan',
    'suisse',
    'gouda',
    'brie',
    'camembert',
    'feta',
    'ricotta',
    'cottage',
    'fromage a la creme',
    'fromage en grains',
    'fromage frais',
    'beurre',
    'margarine',
    'oeuf',
    'oeufs',
    'douzaine d oeufs',
    'blancs d oeufs',
    'milk',
    'cheese',
    'butter',
    'eggs',
    'yogurt',
    'cream',
    'pain',
    'pain tranche',
    'pain blanc',
    'pain de ble',
    'pain multigrain',
    'pain baguette',
    'baguette',
    'ciabatta',
    'pain pita',
    'pita',
    'tortilla',
    'naan',
    'bagel',
    'bagels',
    'muffin',
    'muffin anglais',
    'croissant',
    'brioche',
    'chocolatine',
    'pain a hamburger',
    'pain a hot dog',
    'craquelin',
    'craquelins',
    'biscotte',
    'melba',
    'chapelure',
    'farine',
    'farine tout usage',
    'sucre',
    'cassonade',
    'sucre a glacer',
    'levure',
    'poudre a pate',
    'bicarbonate',
    'preparation a gateau',
    'gateau',
    'tarte',
    'tartelette',
    'beigne',
    'beignes',
    'biscuit',
    'biscuits',
    'gaufre',
    'crepe',
    'cereale',
    'cereales',
    'gruau',
    'avoine',
    'granola',
    'barre tendre',
    'barres tendres',
    'riz',
    'riz basmati',
    'riz brun',
    'couscous',
    'quinoa',
    'orge',
    'lentille',
    'lentilles',
    'pois chiches',
    'haricots noirs',
    'feves au lard',
    'pate alimentaire',
    'pates',
    'spaghetti',
    'macaroni',
    'penne',
    'fusilli',
    'lasagne',
    'nouilles',
    'ramen',
    'vermicelle',
    'bread',
    'flour',
    'sugar',
    'rice',
    'pasta',
    'cereal',
    'huile',
    'huile d olive',
    'huile de canola',
    'huile vegetale',
    'vinaigre',
    'vinaigre balsamique',
    'vinaigrette',
    'sel',
    'poivre',
    'epice',
    'epices',
    'paprika',
    'cumin',
    'cannelle',
    'origan',
    'curcuma',
    'cari',
    'bouillon',
    'bouillon de poulet',
    'soupe',
    'soupe en conserve',
    'conserve',
    'tomates en conserve',
    'pate de tomate',
    'sauce tomate',
    'sauce a spaghetti',
    'sauce',
    'sauce soya',
    'sauce piquante',
    'sriracha',
    'ketchup',
    'moutarde',
    'mayonnaise',
    'relish',
    'salsa',
    'houmous',
    'hummus',
    'trempette',
    'cornichon',
    'cornichons',
    'olives',
    'marinade',
    'confiture',
    'gelee',
    'miel',
    'sirop d erable',
    'sirop de mais',
    'beurre d arachide',
    'tartinade',
    'nutella',
    'cacao',
    'chocolat a cuisson',
    'brisures de chocolat',
    'noix',
    'amande',
    'amandes',
    'arachide',
    'arachides',
    'cajou',
    'pistache',
    'pacane',
    'graines de tournesol',
    'graines de chia',
    'graines de lin',
    'fruits seches',
    'croustille',
    'croustilles',
    'chips',
    'nachos',
    'bretzel',
    'popcorn',
    'mais souffle',
    'noix melangees',
    'bonbon',
    'bonbons',
    'chocolat',
    'barre de chocolat',
    'gomme',
    'jujube',
    'reglisse',
    'friandise',
    'collation',
    'pouding',
    'jello',
    'compote',
    'compote de pommes',
    'yogourt a boire',
    'jus',
    'jus d orange',
    'jus de pomme',
    'jus de raisin',
    'limonade',
    'boisson gazeuse',
    'liqueur douce',
    'coca cola',
    'pepsi',
    'sprite',
    'seven up',
    'ginger ale',
    'club soda',
    'eau petillante',
    'eau minerale',
    'eau embouteillee',
    'caisse d eau',
    'boisson energisante',
    'red bull',
    'gatorade',
    'boisson sportive',
    'the glace',
    'kombucha',
    'surgele',
    'surgeles',
    'legumes surgeles',
    'fruits surgeles',
    'pizza surgelee',
    'pizza congelee',
    'frite',
    'frites',
    'pepites de poulet',
    'poisson pane',
    'pate imperial',
    'dumpling',
    'repas congele',
    'sandwich',
    'sous marin',
    'sushi',
    'salade preparee',
    'plat prepare',
    'rotisserie',
    'couche',
    'couches',
    'lingettes',
    'preparation pour nourrisson',
    'lait maternise',
    'puree pour bebe',
    'papier hygienique',
    'papier de toilette',
    'essuie tout',
    'papier essuie tout',
    'mouchoir',
    'mouchoirs',
    'serviette de table',
    'sac a ordures',
    'sac poubelle',
    'sac ziploc',
    'pellicule plastique',
    'papier d aluminium',
    'papier parchemin',
    'savon a vaisselle',
    'lave vaisselle',
    'detergent',
    'detergent a lessive',
    'savon a linge',
    'assouplissant',
    'feuilles assouplissantes',
    'javel',
    'eau de javel',
    'nettoyant',
    'nettoyant tout usage',
    'nettoyant a vitre',
    'desinfectant',
    'lingettes desinfectantes',
    'eponge',
    'tampon a recurer',
    'chiffon',
    'balai a franges',
    'pile',
    'piles',
    'pile aa',
    'pile aaa',
    'nourriture pour chat',
    'nourriture pour chien',
    'sac reutilisable',
    'sac d epicerie',
    'consigne',
    'depot',
    'vrac',
    'pese',
    'kg',
    'produits',
    'pomme granny',
    'pomme gala',
    'pomme mcintosh',
    'pomme spartan',
    'pomme royal gala',
    'poire bartlett',
    'raisin sans pepin',
    'melon miel vert',
    'petits fruits',
    'barquette de fraises',
    'casseau de fraises',
    'casseau',
    'panier de fruits',
    'clementines boite',
    'citron vert',
    'fruits tropicaux',
    'star fruit',
    'litchi',
    'kaki',
    'goyave',
    'fruit de la passion',
    'canneberges sechees',
    'raisins secs',
    'pruneaux',
    'abricots seches',
    'banane plantain',
    'plantain',
    'mini carottes',
    'carottes rapees',
    'salade cesar kit',
    'kit a salade',
    'coeurs de romaine',
    'mesclun',
    'pousses',
    'germes de soya',
    'feves germees',
    'chou nappa',
    'bok choy',
    'endive',
    'fenouil',
    'artichaut',
    'topinambour',
    'igname',
    'manioc',
    'patates jaunes',
    'patates rouges',
    'patates russet',
    'pommes de terre grelots',
    'oignon espagnol',
    'oignon rouge',
    'oignon jaune',
    'echalote francaise',
    'ail hache',
    'tomates italiennes',
    'tomates de serre',
    'tomate beefsteak',
    'poivron jaune',
    'poivron orange',
    'piment fort',
    'piment banane',
    'courge butternut',
    'courge spaghetti',
    'courge poivree',
    'mais en epi',
    'mais surgele',
    'petits pois',
    'pois verts',
    'haricots jaunes',
    'legumes racines',
    'legumes prepares',
    'plateau de legumes',
    'champignons blancs',
    'champignons cafe',
    'portobello',
    'shiitake',
    'boeuf a fondue',
    'boeuf en cubes',
    'roti de palette',
    'steak de flanc',
    'steak hache',
    'epaule de porc',
    'flanc de porc',
    'porc effiloche',
    'jambon a l os',
    'jambonneau',
    'saucisson',
    'kielbassa',
    'boudin',
    'foie',
    'coeur de veau',
    'escalope',
    'escalope de veau',
    'cotelette d agneau',
    'gigot d agneau',
    'poitrine de dinde',
    'cuisse de dinde',
    'poulet bio',
    'poulet grain',
    'poulet desosse',
    'brochettes de poulet',
    'poulet marine',
    'viande hachee',
    'veau hache',
    'agneau hache',
    'boeuf angus',
    'boeuf vieilli',
    'cotes de boeuf',
    'smoked meat tranche',
    'viande froide',
    'jambon tranche',
    'poitrine de poulet tranchee',
    'simili viande',
    'beyond meat',
    'proteine vegetale texturee',
    'poisson blanc',
    'filet de sole',
    'filet de tilapia',
    'filet de morue',
    'poisson surgele',
    'batonnets de poisson',
    'crevettes nordiques',
    'crevettes tigrees',
    'chair de crabe',
    'queue de homard',
    'palourdes',
    'huitres',
    'escargots',
    'surimi',
    'goberge',
    'hareng',
    'maquereau',
    'anchois',
    'caviar',
    'lait entier',
    'lait 1',
    'lait sans lactose',
    'lait en poudre',
    'lait condense',
    'lait evapore',
    'creme a cafe',
    'creme 10',
    'creme fouettee',
    'creme glacee molle',
    'yogourt nature',
    'yogourt aux fruits',
    'yogourt a boire probiotique',
    'skyr',
    'fromage cheddar fort',
    'fromage cheddar doux',
    'fromage marbre',
    'fromage suisse',
    'fromage havarti',
    'fromage bleu',
    'chevre',
    'fromage de chevre',
    'bocconcini',
    'burrata',
    'mascarpone',
    'fromage en tranches',
    'fromage a fondue',
    'fromage a raclette',
    'oka',
    'fromage oka',
    'fromage en grain frais',
    'beurre sale',
    'beurre non sale',
    'beurre d erable',
    'oeufs bruns',
    'oeufs bio',
    'oeufs omega 3',
    'oeufs de caille',
    'pain de menage',
    'pain aux noix',
    'pain aux raisins',
    'pain sans gluten',
    'pain de seigle',
    'pain au levain',
    'pain hot dog',
    'pain a sous marin',
    'pain naan',
    'focaccia',
    'brioche a la cannelle',
    'pain dore',
    'pate a tarte',
    'pate a pizza',
    'pate feuilletee',
    'pate brisee',
    'chausson',
    'danoise',
    'eclair',
    'millefeuille',
    'macaron',
    'meringue',
    'sucre a la creme',
    'fudge',
    'tarte au sucre',
    'tarte aux pommes',
    'gateau au chocolat',
    'gateau des anges',
    'cupcake',
    'petits gateaux',
    'biscuits soda',
    'biscuits graham',
    'biscuits au chocolat',
    'oreo',
    'petit beurre',
    'galette',
    'muffins anglais',
    'croutons',
    'chapelure panko',
    'farine de ble entier',
    'farine sans gluten',
    'semoule',
    'fecule de mais',
    'levure chimique',
    'sucre blanc',
    'sucre brun',
    'sucre d erable',
    'edulcorant',
    'stevia',
    'sel de mer',
    'gros sel',
    'fleur de sel',
    'poivre noir',
    'poivre moulu',
    'melange d epices',
    'epices a steak',
    'herbes de provence',
    'feuille de laurier',
    'clou de girofle',
    'muscade',
    'gingembre moulu',
    'curcuma moulu',
    'safran',
    'graines de sesame',
    'levure alimentaire',
    'bouillon de boeuf',
    'bouillon de legumes',
    'fond de veau',
    'sauce demi glace',
    'sauce hollandaise',
    'sauce alfredo',
    'sauce rosee',
    'sauce bolognaise',
    'sauce barbecue',
    'sauce worcestershire',
    'sauce poisson',
    'sauce huitre',
    'sauce teriyaki',
    'sauce aux prunes',
    'sauce a poutine',
    'sauce brune',
    'vinaigre de vin',
    'vinaigre de cidre',
    'vinaigre blanc',
    'huile de sesame',
    'huile de coco',
    'huile d arachide',
    'huile de tournesol',
    'shortening',
    'saindoux',
    'cafe moulu format',
    'the en sachet',
    'the earl grey',
    'the camomille',
    'infusion',
    'chocolat chaud en poudre',
    'poudre de cacao',
    'sirop aromatise',
    'cristaux a saveur',
    'boisson en poudre',
    'eau de coco',
    'jus de legumes',
    'jus de canneberge',
    'jus de tomate',
    'cocktail de fruits',
    'punch aux fruits',
    'boisson au soya',
    'boisson au riz',
    'smoothie',
    'yop',
    'eau aromatisee',
    'perrier',
    'san pellegrino',
    'canada dry',
    'mountain dew',
    'dr pepper',
    'root beer',
    'creme soda',
    'orangeade',
    'boisson gazeuse diete',
    'boisson gazeuse zero',
    'caisse de 12',
    'caisse de 24',
    'bouteille de 2 l',
    'pizza pochette',
    'burritos surgeles',
    'mini pizzas',
    'croquettes de poulet',
    'rondelles d oignon',
    'pommes de terre rissolees',
    'galettes de pommes de terre',
    'hash brown',
    'legumes melanges surgeles',
    'brocoli surgele',
    'epinards surgeles',
    'petits fruits surgeles',
    'creme glacee contenant',
    'sandwich creme glacee',
    'popsicle',
    'sorbet',
    'yogourt glace',
    'gateau surgele',
    'tarte surgelee',
    'pate a biscuits',
    'pate a pain congelee',
    'repas asiatique surgele',
    'riz frit surgele',
    'mets prepares',
    'poulet barbecue',
    'salade de chou',
    'salade de macaroni',
    'salade de patates',
    'plateau de fromages',
    'plateau de charcuteries',
    'sushi comptoir',
    'poke pret',
    'sandwich pret',
    'cereales granola',
    'cereales au son',
    'flocons de mais',
    'riz souffle',
    'muesli',
    'gruau instantane',
    'barres dejeuner',
    'barre proteinee',
    'melange du randonneur',
    'noix de grenoble',
    'noix du bresil',
    'noisette',
    'graines de citrouille',
    'beurre d amande',
    'tahini',
    'confiture de fraises',
    'gelee de raisin',
    'tartinade au chocolat',
    'sirop de table',
    'sirop de poteau',
    'miel cremeux',
    'melasse',
    'essuie tout format',
    'papier hygienique 12',
    'mouchoirs boite',
    'serviettes de table',
    'assiettes de carton',
    'verres de plastique',
    'ustensiles jetables',
    'sacs a sandwich',
    'sacs de congelation',
    'papier ciree',
    'contenants alimentaires',
    'filtres a cafe',
    'sac aspirateur',
    'savon a mains liquide',
    'savon en barre',
    'nettoyant salle de bain',
    'nettoyant plancher',
    'vinaigre menager',
    'bicarbonate menager',
    'detachant',
    'amidon',
    'boules a laver',
    'capsules a lessive',
    'pastilles lave vaisselle',
    'rince vaisselle',
    'desodorisant',
    'assainisseur d air',
    'chandelle menage',
    'insecticide',
    'piege a souris',
    'boules a mites',
    'papier collant a mouches',
    'aliments pour bebe',
    'cereales pour bebe',
    'collation pour bebe',
    'biberon',
    'suce',
    'creme pour couche',
    'lingettes pour bebe',
    'couches taille 3',
    'couches taille 4',
    'couches de nuit',
    'culottes de proprete',
    'kraft',
    'heinz',
    'campbell',
    'catelli',
    'barilla',
    'primo',
    'uncle ben',
    'minute rice',
    'quaker',
    'kellogg',
    'cheerios',
    'special k',
    'nutella pot',
    'nutrigrain',
    'general mills',
    'danone',
    'yoplait',
    'iogo',
    'liberte',
    'activia',
    'natrel',
    'quebon',
    'lactantia',
    'beatrice',
    'agropur',
    'saputo',
    'black diamond',
    'armstrong',
    'cracker barrel',
    'philadelphia',
    'becel',
    'olivina',
    'crisco',
    'olymel',
    'lafleur charcuterie',
    'maple leaf',
    'schneiders',
    'exceldor',
    'flamingo',
    'st-hubert sauce',
    'cordon bleu',
    'lassonde',
    'oasis',
    'tropicana',
    'rougemont',
    'del monte',
    'dole',
    'sunrype',
    'mott',
    'clamato',
    'gatorade bouteille',
    'powerade',
    'vitaminwater',
    'eska',
    'naya',
    'labrador eau',
    'aquafina',
    'dasani',
    'montellier',
    'president choice',
    'choix du president',
    'sans nom',
    'no name',
    'irresistibles',
    'compliments',
    'great value',
    'kirkland',
    'marque maison',
    'biologique',
    'bio',
    'sans gluten',
    'vegan',
    'vegetalien',
    'keto',
    'format familial',
    'format economique',
    'emballage de 6',
    'paquet de 4',
    'milk 2',
    'chicken breast',
    'cheddar cheese',
    'orange juice',
    'apple juice',
    'frozen pizza',
    'ice cream',
    'paper towel',
    'toilet paper',
    'laundry detergent',
    'dish soap',
    'peanut butter',
    'canned soup',
    'olive oil',
    'granola bar',
    'snack',
    'beverage',
    'produce dept',
    'deli dept',
    'bakery dept',
    'meat dept',
  ],
  restaurant: [
    'entree',
    'plat principal',
    'table d hote',
    'menu du jour',
    'special du midi',
    'trio',
    'combo',
    'burger',
    'hamburger',
    'cheeseburger',
    'big mac',
    'whopper',
    'frites moyennes',
    'frites grandes',
    'poutine',
    'poutine italienne',
    'hot dog',
    'steamie',
    'michigan',
    'guedille',
    'club sandwich',
    'wrap',
    'panini',
    'bagel dejeuner',
    'dejeuner',
    'oeufs benedictine',
    'omelette',
    'crepes',
    'gaufres',
    'pizza',
    'pizza large',
    'pizza medium',
    'pizza toute garnie',
    'pepperoni fromage',
    'calzone',
    'spaghetti sauce viande',
    'fettuccine alfredo',
    'lasagne maison',
    'pates du jour',
    'salade cesar',
    'salade grecque',
    'soupe du jour',
    'soupe tonkinoise',
    'pho',
    'general tao',
    'poulet general tao',
    'riz frit',
    'chow mein',
    'egg roll',
    'won ton',
    'sushi maki',
    'maki',
    'sashimi',
    'nigiri',
    'poke bowl',
    'pad thai',
    'curry',
    'butter chicken',
    'shish taouk',
    'shawarma',
    'souvlaki',
    'gyro',
    'falafel',
    'tacos',
    'burrito',
    'quesadilla',
    'nachos supreme',
    'ailes buffalo',
    'cotes levees bbq',
    'filet de porc',
    'brochette',
    'fondue',
    'raclette',
    'tartare',
    'moules frites',
    'fish and chips',
    'poulet frit',
    'quart de poulet',
    'demi poulet',
    'sauce bbq',
    'trempette ranch',
    'dessert',
    'sundae',
    'milkshake',
    'lait frappe',
    'gateau au fromage',
    'creme brulee',
    'tiramisu',
    'brownie',
    'breuvage',
    'boisson gazeuse moyenne',
    'refill',
    'service',
    'pourboire',
    'gratuite',
    'tps tvq repas',
    'pour emporter',
    'sur place',
    'livraison',
    'couvert',
    'serveur',
    'addition',
    'assiette du chef',
    'menu enfant',
    'repas complet',
    'portion',
    'extra fromage',
    'extra bacon',
    'accompagnement',
    'salade du chef',
    'salade repas',
    'bol repas',
    'bol de riz',
    'assiette froide',
    'grillades',
    'cote de boeuf',
    'filet de boeuf',
    'surf and turf',
    'vol au vent',
    'pate chinois',
    'ragout de boulettes',
    'tourtiere',
    'feves au lard maison',
    'soupe aux pois',
    'creton maison',
    'oreilles de crisse',
    'dejeuner complet',
    'deux oeufs bacon',
    'saucisses dejeuner',
    'fruits dejeuner',
    'toast',
    'roties',
    'smoothie dejeuner',
    'cafe inclus',
    'table d hote soir',
    'menu degustation',
    'apportez votre vin',
    'entrees a partager',
    'bruschetta',
    'calmars frits',
    'escargots gratines',
    'soupe a l oignon',
    'chaudree',
    'bisque',
    'tartare de saumon',
    'ceviche',
    'carpaccio',
    'pizza vegetarienne',
    'pizza hawaienne',
    'pizza all dressed',
    'all dressed',
    'sous marin 12',
    'sous marin 6',
    'sandwich au poulet',
    'grilled cheese',
    'hot chicken',
    'hot hamburger',
    'poutine galvaude',
    'poutine bacon',
    'frites sauce',
    'frites poutine',
    'rondelle d oignon',
    'salade cesar poulet',
    'wrap poulet',
    'burrito bowl',
    'quesadilla poulet',
    'ailes de poulet 12',
    'cotes levees pleine',
    'brochette de poulet',
    'riz basmati accompagnement',
    'naan a l ail',
    'samosa',
    'pakora',
    'biryani',
    'vindaloo',
    'tikka masala',
    'pho boeuf',
    'bo bun',
    'rouleau de printemps',
    'rouleau imperial',
    'dumplings vapeur',
    'bao',
    'bibimbap',
    'bulgogi',
    'kimchi',
    'sushi combo',
    'plateau de sushis',
    'dragon roll',
    'california roll',
    'spicy salmon',
    'tempura',
    'gyoza',
    'edamame',
    'miso',
    'udon',
    'yakisoba',
    'poulet au beurre',
    'couscous royal',
    'tajine',
    'kebab',
    'assiette grecque',
    'tzatziki',
    'feta grecque',
    'moussaka',
    'paella',
    'tapas',
    'empanada',
    'pupusa',
    'arepa',
    'jerk chicken',
    'riz et pois',
    'boisson incluse',
    'the glace maison',
    'limonade maison',
    'verre de vin maison',
    'biere en fut',
    'cafe expresso resto',
    'dessert du jour',
    'gateau moelleux',
    'pouding chomeur',
    'tarte au sucre resto',
    'creme glacee dessert',
    'profiterole',
  ],
  'livraison-repas': ['frais de livraison', 'frais de service', 'pourboire livreur', 'commande'],
  cafe: [
    'cafe',
    'cafe filtre',
    'cafe allonge',
    'espresso',
    'double espresso',
    'americano',
    'latte',
    'cafe latte',
    'cappuccino',
    'macchiato',
    'moka',
    'flat white',
    'cortado',
    'cafe au lait',
    'cafe glace',
    'cafe froid',
    'cold brew',
    'frappuccino',
    'chai latte',
    'matcha latte',
    'the',
    'the vert',
    'the noir',
    'tisane',
    'chocolat chaud',
    'petit format',
    'moyen format',
    'grand format',
    'extra large',
    'lait de soya supplement',
    'shot supplementaire',
    'muffin cafe',
    'scone',
    'biscotti',
    'timbits',
    'roulee',
    'grains de cafe',
    'cafe moulu',
    'capsule',
    'capsules',
    'dosette',
    'keurig',
    'k cup',
    'nespresso',
    'cafe noir',
    'cafe regulier',
    'cafe deux creme',
    'double double',
    'cafe decafeine',
    'decaf',
    'ristretto',
    'lungo',
    'affogato',
    'latte vanille',
    'latte caramel',
    'latte epice citrouille',
    'moka blanc',
    'chocolat blanc chaud',
    'the london fog',
    'the chai',
    'matcha',
    'the vert glace',
    'limonade glacee',
    'refresher',
    'smoothie fruits',
    'boisson glacee',
    'supplement sirop',
    'lait avoine supplement',
    'croissant amandes',
    'chausson aux pommes',
    'brioche cannelle',
    'muffin bleuets',
    'muffin son',
    'bagel fromage a la creme',
    'sandwich dejeuner',
    'wrap dejeuner',
    'biscuit avoine',
    'carre au chocolat',
    'beigne glace',
    'beigne sucre',
    'boite de 12 beignes',
    'cafe format moyen',
    'tasse reutilisable',
    'sac de cafe',
    'cafe en grains 1 kg',
    'moulure espresso',
    'capsules compatibles',
  ],
  alcool: [
    'biere',
    'bieres',
    'caisse de biere',
    'douze biere',
    'vingt quatre',
    'ipa',
    'lager',
    'pilsner',
    'blonde',
    'rousse',
    'blanche',
    'stout',
    'porter',
    'ale',
    'biere de microbrasserie',
    'bud light',
    'coors',
    'molson',
    'labatt',
    'heineken',
    'corona',
    'stella',
    'guinness',
    'boreale',
    'unibroue',
    'belle gueule',
    'saint ambroise',
    'vin',
    'vin rouge',
    'vin blanc',
    'vin rose',
    'mousseux',
    'champagne',
    'prosecco',
    'cava',
    'chardonnay',
    'sauvignon blanc',
    'pinot grigio',
    'pinot noir',
    'merlot',
    'cabernet',
    'cabernet sauvignon',
    'malbec',
    'shiraz',
    'syrah',
    'riesling',
    'sangria',
    'cidre',
    'cidre de glace',
    'vin de glace',
    'spiritueux',
    'vodka',
    'gin',
    'rhum',
    'rhum brun',
    'tequila',
    'whisky',
    'whiskey',
    'scotch',
    'bourbon',
    'cognac',
    'brandy',
    'porto',
    'vermouth',
    'liqueur',
    'baileys',
    'amaretto',
    'sambuca',
    'aperol',
    'campari',
    'jack daniels',
    'smirnoff',
    'absolut',
    'bacardi',
    'captain morgan',
    'jameson',
    'crown royal',
    'cocktail',
    'pret a boire',
    'seltzer',
    'hard seltzer',
    'white claw',
    'panache',
    'sortilege',
    'pinte',
    'demi pinte',
    'pichet',
    'verre de vin',
    'bouteille de vin',
    'shooter',
    'shot',
    'consigne bouteille',
    'biere blonde',
    'biere rousse',
    'biere blanche',
    'biere noire',
    'biere sans alcool',
    'biere de ble',
    'double ipa',
    'neipa',
    'session ipa',
    'gose',
    'sour',
    'saison',
    'trappiste',
    'kolsch',
    'amber',
    'pale ale',
    'india pale ale',
    'canette de biere',
    'bouteille de biere',
    '6 pack',
    '12 pack',
    '24 pack',
    'growler',
    'biere en fut maison',
    'vin maison',
    'vin biologique',
    'vin nature',
    'vin orange',
    'vin de dessert',
    'vin fortifie',
    'sauternes',
    'chianti',
    'rioja',
    'bordeaux',
    'bourgogne',
    'beaujolais',
    'cotes du rhone',
    'valpolicella',
    'amarone',
    'barolo',
    'tempranillo',
    'grenache',
    'zinfandel',
    'gewurztraminer',
    'moscato',
    'vinho verde',
    'rose de provence',
    'boite de vin',
    'vin en vrac',
    'bag in box',
    'gin quebecois',
    'vodka premium',
    'rhum epice',
    'tequila blanco',
    'mezcal',
    'whisky canadien',
    'single malt',
    'rye',
    'triple sec',
    'cointreau',
    'kahlua',
    'creme irlandaise',
    'pastis',
    'absinthe',
    'sake',
    'soju',
    'cocktail pret a boire',
    'mojito',
    'margarita',
    'cesar',
    'bloody mary',
    'spritz',
    'punch alcoolise',
    'cooler',
    'smirnoff ice',
    'palm bay',
    'mott clamato cocktail',
  ],
  vehicule: [],
  essence: [
    'essence',
    'ordinaire',
    'super',
    'supreme',
    'diesel',
    'litre',
    'litres',
    'prix au litre',
    'pompe no',
    'sans plomb',
    'ethanol',
    'lave glace',
    'regular',
    'premium',
    'fuel',
    'gas',
    'essence ordinaire',
    'essence super',
    'sans plomb 87',
    'sans plomb 89',
    'sans plomb 91',
    'diesel clair',
    'additif',
    'nettoyant injecteur',
    'prix par litre',
    'montant essence',
    'pompe 1',
    'pompe 2',
  ],
  'assurance-auto': [],
  'entretien-vehicule': [
    'changement d huile',
    'vidange d huile',
    'huile moteur',
    'filtre a huile',
    'filtre a air',
    'filtre a habitacle',
    'bougies d allumage',
    'balai d essuie glace',
    'essuie glace',
    'antigel',
    'liquide de refroidissement',
    'liquide a frein',
    'plaquette de frein',
    'frein',
    'freins',
    'disque de frein',
    'rotor',
    'pneu',
    'pneus',
    'pneus d hiver',
    'pneus d ete',
    'entreposage de pneus',
    'installation de pneus',
    'balancement',
    'alignement',
    'batterie de voiture',
    'alternateur',
    'demarreur',
    'silencieux',
    'echappement',
    'suspension',
    'amortisseur',
    'courroie',
    'inspection',
    'diagnostic',
    'main d oeuvre',
    'lavage auto',
    'lave auto',
    'cirage',
    'traitement antirouille',
    'huile 5w30',
    'huile 0w20',
    'huile synthetique',
    'filtre a essence',
    'liquide lave glace',
    'liquide de transmission',
    'liquide de direction',
    'graissage',
    'mise au point',
    'verification 21 points',
    'pneus 4 saisons',
    'valve tpms',
    'capteur',
    'ampoule de phare',
    'phare avant',
    'feu arriere',
    'essuie glace arriere',
    'tapis d auto',
    'housse de siege',
    'desodorisant auto',
    'cire a auto',
    'shampoing a auto',
    'aspirateur auto',
    'grattoir',
    'cable de survoltage',
    'boitier de demarrage',
    'chaine a neige',
  ],
  stationnement: ['heure de stationnement', 'espace', 'borne', 'vignette', 'place'],
  'transport-commun': ['passe mensuelle', 'titre de transport', 'billet', 'correspondance', 'opus'],
  taxi: ['course', 'trajet', 'attente', 'frais de base'],
  medicaments: [
    'ordonnance',
    'prescription',
    'medicament',
    'comprime',
    'comprimes',
    'gelule',
    'sirop',
    'acetaminophene',
    'tylenol',
    'advil',
    'ibuprofene',
    'aspirine',
    'antihistaminique',
    'benadryl',
    'reactine',
    'claritin',
    'sirop contre la toux',
    'pastille pour la gorge',
    'decongestionnant',
    'antiacide',
    'tums',
    'pepto',
    'laxatif',
    'imodium',
    'polysporin',
    'onguent',
    'creme antibiotique',
    'pansement',
    'diachylon',
    'bandage',
    'gaze',
    'ruban medical',
    'thermometre',
    'test de grossesse',
    'test covid',
    'masque de procedure',
    'desinfectant a mains',
    'vitamine',
    'vitamines',
    'vitamine d',
    'multivitamine',
    'calcium',
    'fer',
    'magnesium',
    'omega 3',
    'probiotique',
    'melatonine',
    'supplement',
    'proteine en poudre',
    'creatine',
    'sirop pour enfants',
    'tempra',
    'motrin',
    'gravol',
    'buckley',
    'vicks',
    'halls',
    'fisherman friend',
    'nyquil',
    'dayquil',
    'sudafed',
    'otrivin',
    'spray nasal',
    'solution saline',
    'gouttes pour les yeux',
    'visine',
    'systane',
    'gouttes auriculaires',
    'creme cortisone',
    'hydrocortisone',
    'creme antifongique',
    'canesten',
    'monistat',
    'lax a day',
    'restoralax',
    'metamucil',
    'senokot',
    'gaviscon',
    'zantac',
    'omeprazole',
    'antibiotique',
    'amoxicilline',
    'inhalateur',
    'ventolin',
    'epipen',
    'insuline',
    'bandelettes glycemie',
    'lancettes',
    'tensiometre',
    'compresse',
    'attelle',
    'genouillere',
    'bas de compression',
    'beguille',
    'sac de glace',
    'sac magique',
    'chauffe main',
    'huile de foie de morue',
    'vitamine c',
    'vitamine b12',
    'zinc',
    'collagene',
    'glucosamine',
    'curcumine',
    'ashwagandha',
    'proteine vegetale poudre',
    'electrolytes',
    'pedialyte',
    'boost',
    'ensure',
  ],
  'soins-medicaux': [
    'consultation',
    'examen',
    'traitement',
    'seance',
    'frais de dossier',
    'consultation initiale',
    'consultation de suivi',
    'traitement de physio',
    'seance de massage',
    'examen de la vue',
    'verres correcteurs',
    'monture',
    'verres de contact',
    'solution a lentilles',
    'prothese auditive',
    'pile pour appareil auditif',
    'orthese plantaire',
    'bas medicaux',
    'frais de rapport medical',
    'note du medecin',
    'test sanguin',
    'analyse d urine',
    'depistage',
  ],
  dentiste: [
    'nettoyage dentaire',
    'detartrage',
    'examen dentaire',
    'radiographie',
    'obturation',
    'plombage',
    'extraction',
    'couronne',
    'traitement de canal',
    'fluorure',
    'examen de rappel',
    'polissage',
    'scellant dentaire',
    'obturation composite',
    'obturation amalgame',
    'extraction de dent de sagesse',
    'chirurgie buccale',
    'implant',
    'pont dentaire',
    'protheses complete',
    'reparation de prothese',
    'gouttiere occlusale',
    'protecteur buccal',
    'blanchiment',
    'urgence dentaire',
  ],
  sport: [
    'abonnement mensuel',
    'entrainement',
    'cours de groupe',
    'seance privee',
    'haltere',
    'halteres',
    'kettlebell',
    'tapis de yoga',
    'bande elastique',
    'corde a sauter',
    'ballon d exercice',
    'gourde',
    'espadrille',
    'espadrilles',
    'souliers de course',
    'legging',
    'brassiere de sport',
    'short de sport',
    'maillot de bain',
    'lunettes de natation',
    'raquette',
    'balle de tennis',
    'ballon de basketball',
    'ballon de soccer',
    'baton de hockey',
    'rondelle',
    'patins',
    'casque',
    'skis',
    'planche a neige',
    'velo',
    'chambre a air',
    'pompe a velo',
    'chaussures d entrainement',
    'gants de gym',
    'ceinture d halterophilie',
    'sangle',
    'rouleau de massage',
    'balle de massage',
    'tapis d exercice',
    'banc de musculation',
    'barre de traction',
    'poids',
    'disque',
    'velo stationnaire',
    'tapis roulant',
    'elliptique',
    'rameur',
    'montre de sport',
    'cardiofrequencemetre',
    'bouteille d eau sport',
    'shaker',
    'sac de sport',
    'serviette de sport',
    'protege dents',
    'jambieres',
    'epaulettes',
    'gants de hockey',
    'culotte de hockey',
    'bas de hockey',
    'ruban a hockey',
    'affutage de patins',
    'balle de golf',
    'te de golf',
    'gant de golf',
    'batons de golf',
    'raquette de badminton',
    'volant',
    'ballon de volleyball',
    'ballon de football',
    'gant de baseball',
    'casque de velo',
    'cuissard',
    'maillot de velo',
    'gourde de velo',
    'cadenas de velo',
    'porte velo',
    'skis alpins',
    'fixations',
    'batons de ski',
    'lunettes de ski',
    'casque de ski',
    'billet de remontee',
    'billet de ski',
    'location d equipement',
  ],
  vetements: [
    'chandail',
    't shirt',
    'tshirt',
    'camisole',
    'debardeur',
    'chemise',
    'blouse',
    'polo',
    'pull',
    'chandail a capuchon',
    'hoodie',
    'coton ouate',
    'cardigan',
    'veste',
    'manteau',
    'parka',
    'impermeable',
    'coupe vent',
    'pantalon',
    'jeans',
    'jean',
    'chino',
    'short',
    'bermuda',
    'jupe',
    'robe',
    'combinaison',
    'complet',
    'veston',
    'cravate',
    'ceinture',
    'bas',
    'chaussette',
    'chaussettes',
    'collant',
    'sous vetement',
    'boxer',
    'culotte',
    'soutien gorge',
    'pyjama',
    'robe de chambre',
    'tuque',
    'casquette',
    'chapeau',
    'foulard',
    'mitaine',
    'mitaines',
    'gants',
    'chaussure',
    'chaussures',
    'soulier',
    'souliers',
    'botte',
    'bottes',
    'sandale',
    'sandales',
    'pantoufle',
    'sac a main',
    'sac a dos',
    'portefeuille',
    'lunettes de soleil',
    'montre',
    'bijou',
    'collier',
    'bracelet',
    'boucles d oreilles',
    'taille',
    'grandeur',
    'small',
    'medium',
    'large',
    'chandail manches longues',
    'chandail col rond',
    'chemise a carreaux',
    'veste de jean',
    'manteau d hiver',
    'manteau de printemps',
    'habit de neige',
    'salopette',
    'pantalon de neige',
    'pantalon cargo',
    'leggings',
    'jogging',
    'ensemble molletonne',
    'camisole de sport',
    'bas de laine',
    'bas de compression sport',
    'chaussettes de sport',
    'sous vetement thermique',
    'combinaison thermique',
    'tuque et mitaines',
    'cache cou',
    'cagoule',
    'bottes d hiver',
    'bottes de pluie',
    'bottes de travail',
    'chaussures de securite',
    'chaussures de ville',
    'espadrilles de course',
    'sandales de plage',
    'gougounes',
    'claquettes',
    'pantoufles',
    'chaussons',
    'maillot une piece',
    'bikini',
    'short de bain',
    'pyjama enfant',
    'grenouillere',
    'cache couche',
    'bavoir',
    'bonnet bebe',
    'chapeau de soleil',
    'casquette ajustable',
    'tuque en laine',
    'gants de cuir',
    'ceinture en cuir',
    'cravate soie',
    'noeud papillon',
    'bretelles',
    'sac fourre tout',
    'sac bandouliere',
    'porte monnaie',
    'porte cles',
    'etui a lunettes',
  ],
  'soins-personnels': [
    'shampoing',
    'shampooing',
    'revitalisant',
    'apres shampoing',
    'gel coiffant',
    'mousse coiffante',
    'laque',
    'coloration',
    'teinture a cheveux',
    'savon',
    'savon corporel',
    'gel douche',
    'pain de savon',
    'savon a mains',
    'deodorant',
    'antisudorifique',
    'dentifrice',
    'brosse a dents',
    'soie dentaire',
    'rince bouche',
    'listerine',
    'creme hydratante',
    'lotion',
    'hydratant visage',
    'creme solaire',
    'ecran solaire',
    'baume a levres',
    'nettoyant visage',
    'demaquillant',
    'serum',
    'masque visage',
    'rasoir',
    'lames de rasoir',
    'gel a raser',
    'mousse a raser',
    'apres rasage',
    'cire epilatoire',
    'coupe ongles',
    'lime a ongles',
    'vernis a ongles',
    'dissolvant',
    'maquillage',
    'fond de teint',
    'poudre',
    'fard a joues',
    'mascara',
    'crayon a sourcils',
    'ombre a paupieres',
    'rouge a levres',
    'brillant a levres',
    'parfum',
    'eau de toilette',
    'coton',
    'tampon demaquillant',
    'coton tige',
    'serviette hygienique',
    'tampon',
    'protege dessous',
    'coupe menstruelle',
    'coupe de cheveux',
    'coloriste',
    'mise en plis',
    'barbe',
    'manucure',
    'pedicure',
    'massage',
    'facial',
    'epilation',
    'shampoing secheresse',
    'shampoing antipelliculaire',
    'head and shoulders',
    'pantene',
    'dove',
    'nivea',
    'vaseline',
    'aveeno',
    'cetaphil',
    'cerave',
    'la roche posay',
    'neutrogena',
    'olay',
    'garnier',
    'l oreal',
    'maybelline',
    'revlon',
    'covergirl',
    'nyx',
    'essence maquillage',
    'axe',
    'old spice',
    'gillette',
    'schick',
    'venus',
    'bic rasoir',
    'secret deodorant',
    'degree',
    'colgate',
    'crest',
    'sensodyne',
    'oral b',
    'brosse a dents electrique',
    'tete de rechange',
    'fil de soie',
    'cure dents',
    'gratte langue',
    'seche cheveux',
    'fer plat',
    'fer a boucler',
    'tondeuse a barbe',
    'pince a epiler',
    'miroir grossissant',
    'brosse a cheveux',
    'peigne',
    'elastiques a cheveux',
    'pinces a cheveux',
    'bonnet de douche',
    'gant de toilette',
    'sels de bain',
    'bombe de bain',
    'huile essentielle',
    'creme pour les mains',
    'creme pour les pieds',
    'talc',
    'anti frisottis',
    'gel douche homme',
    'mousse nettoyante',
  ],
  streaming: [
    'abonnement',
    'forfait mensuel',
    'renouvellement',
    'abonnement standard',
    'abonnement premium',
    'abonnement familial',
    'essai gratuit',
    'renouvellement mensuel',
    'renouvellement annuel',
    'forfait annuel',
    'acces illimite',
  ],
  'jeux-video': [
    'jeu',
    'jeu video',
    'manette',
    'console',
    'carte cadeau psn',
    'carte cadeau xbox',
    'abonnement game pass',
    'playstation plus',
    'nintendo switch',
    'cartouche',
    'monnaie virtuelle',
    'v bucks',
    'robux',
    'casque de jeu',
    'clavier',
    'souris',
    'tapis de souris',
    'jeu ps5',
    'jeu xbox series',
    'jeu switch',
    'jeu pc',
    'abonnement en ligne',
    'dlc',
    'extension de jeu',
    'passe de combat',
    'battle pass',
    'microtransaction',
    'manette sans fil',
    'manette pro',
    'joy con',
    'casque gamer',
    'micro casque',
    'webcam',
    'carte graphique',
    'disque dur externe',
    'carte memoire',
    'station de recharge',
    'chaise gamer',
  ],
  sorties: [
    'billet adulte',
    'billet enfant',
    'entree generale',
    'admission',
    'siege',
    'rangee',
    'popcorn grand',
    'mais souffle grand',
    'cinema',
    'spectacle',
    'concert',
    'festival',
    'musee',
    'exposition',
    'quilles',
    'partie',
    'location de film',
    'vestiaire',
    'frais de billetterie',
    'billet aine',
    'billet etudiant',
    'forfait famille',
    'abonnement saison',
    'laissez passer',
    'passeport annuel',
    'visite libre',
    'audioguide',
    'casier',
    'location de patins',
    'location de quilles',
    'souliers de quilles',
    'partie de billard',
    'boisson incluse spectacle',
    'programme souvenir',
    'chandail souvenir',
    'affiche du spectacle',
    'frais de service billetterie',
  ],
  lecture: [
    'livre',
    'roman',
    'bande dessinee',
    'manga',
    'livre de poche',
    'couverture rigide',
    'revue',
    'magazine',
    'journal',
    'abonnement papier',
    'livre audio',
    'livre numerique',
    'ebook',
    'cahier',
    'agenda',
    'roman policier',
    'roman jeunesse',
    'livre pour enfants',
    'album illustre',
    'livre de recettes',
    'livre de cuisine',
    'guide de voyage',
    'essai',
    'biographie',
    'poesie',
    'dictionnaire',
    'grammaire',
    'manuel scolaire',
    'cahier d activites',
    'revue scientifique',
    'hebdomadaire',
    'quotidien',
    'abonnement numerique',
    'carte cadeau librairie',
    'signet',
    'liseuse',
  ],
  voyages: [
    'nuitee',
    'nuit',
    'chambre',
    'occupation double',
    'taxe d hebergement',
    'frais de resort',
    'vol',
    'billet d avion',
    'bagage enregistre',
    'bagage supplementaire',
    'selection de siege',
    'location de voiture',
    'assurance voyage',
    'forfait',
    'excursion',
    'transfert aeroport',
    'valise',
    'passeport',
    'chambre double',
    'chambre king',
    'suite',
    'petit dejeuner inclus',
    'stationnement hotel',
    'frais d hebergement',
    'nuit supplementaire',
    'surclassement',
    'siege avec espace',
    'bagage a main',
    'franchise bagage',
    'wifi a bord',
    'repas a bord',
    'carte d embarquement',
    'assurance annulation',
    'frais de reservation',
    'taxe d aeroport',
    'navette',
    'location vehicule intermediaire',
    'kilometrage illimite',
    'essence prepayee',
    'peage',
    'carte routiere',
    'adaptateur de voyage',
    'valise cabine',
    'sac de voyage',
    'cadenas tsa',
    'oreiller de voyage',
    'trousse de voyage',
  ],
  'garde-enfants': [
    'garde',
    'frais de garde',
    'journee de garde',
    'camp de jour',
    'gardienne',
    'service de garde',
    'frais hebdomadaire',
    'inscription camp',
    'semaine de camp',
    'service de garde matin',
    'service de garde soir',
    'journee pedagogique',
    'sortie du camp',
    'chandail de camp',
    'depot d inscription',
  ],
  animaux: [
    'nourriture pour chien',
    'nourriture pour chat',
    'moulee',
    'croquettes',
    'pate pour chat',
    'gaterie',
    'os a macher',
    'litiere',
    'litiere pour chat',
    'sac a crotte',
    'laisse',
    'collier pour chien',
    'harnais',
    'jouet pour chien',
    'jouet pour chat',
    'griffoir',
    'cage',
    'aquarium',
    'foin',
    'graines pour oiseaux',
    'vaccin',
    'vermifuge',
    'antipuces',
    'toilettage',
    'consultation veterinaire',
    'nourriture seche',
    'nourriture humide',
    'conserve pour chien',
    'conserve pour chat',
    'sac de moulee',
    'gaterie dentaire',
    'os pour chien',
    'biscuits pour chien',
    'herbe a chat',
    'cataire',
    'litiere agglomerante',
    'bac a litiere',
    'pelle a litiere',
    'shampoing pour chien',
    'brosse pour animaux',
    'coupe griffes',
    'collier antipuces',
    'medaille',
    'manteau pour chien',
    'bottines pour chien',
    'bol pour animaux',
    'fontaine a eau',
    'cage de transport',
    'niche',
    'lit pour chien',
    'coussin pour chat',
    'arbre a chat',
    'jouet couineur',
    'balle pour chien',
    'frisbee',
    'laisse retractable',
    'harnais anti traction',
    'museliere',
    'graines pour perruche',
    'foin pour lapin',
    'copeaux',
    'nourriture pour poisson',
    'conditionneur d eau',
    'filtre d aquarium',
  ],
  'cadeaux-offerts': [
    'carte cadeau',
    'certificat cadeau',
    'emballage cadeau',
    'papier d emballage',
    'carte cadeau 25',
    'carte cadeau 50',
    'carte cadeau 100',
    'sac cadeau',
    'boucle cadeau',
    'ruban cadeau',
    'carte de souhaits',
    'chocolat en boite',
    'panier gourmand',
    'fleurs coupees',
    'bouquet mixte',
    'plante cadeau',
    'toutou',
    'jouet cadeau',
    'bougie cadeau',
  ],
  dons: ['don', 'contribution', 'recu de don'],
  scolarite: [
    'frais de scolarite',
    'droits de scolarite',
    'session',
    'credit',
    'cahier d exercices',
    'manuel',
    'materiel scolaire',
    'crayon',
    'stylo',
    'surligneur',
    'gomme a effacer',
    'regle',
    'calculatrice',
    'cartable',
    'duo tang',
    'feuilles mobiles',
    'colle en baton',
    'ciseaux',
    'cartable 3 anneaux',
    'reliure',
    'pochettes protectrices',
    'separateurs',
    'cahier ligne',
    'cahier quadrille',
    'cahier canada',
    'crayon a mine',
    'crayons de couleur',
    'crayons feutres',
    'marqueur permanent',
    'correcteur liquide',
    'ruban correcteur',
    'taille crayon',
    'etui a crayons',
    'compas',
    'rapporteur d angles',
    'equerre',
    'calculatrice scientifique',
    'calculatrice graphique',
    'papier construction',
    'carton',
    'colle blanche',
    'batons de colle',
    'brocheuse',
    'brocheuses agrafes',
    'perforatrice',
    'trombones',
    'post it',
    'papier imprimante',
    'cartouche d encre',
    'sac a dos ecolier',
    'boite a lunch scolaire',
    'gourde ecole',
    'uniforme',
    'espadrilles d education physique',
  ],
  formation: [
    'inscription',
    'cours',
    'atelier',
    'certification',
    'frais d examen',
    'materiel de cours',
    'manuel de formation',
    'acces plateforme',
    'licence etudiante',
    'cours theorique',
    'cours pratique',
    'heures de conduite',
    'renouvellement de certification',
  ],
  epargne: [],
  'remboursement-dette': [],
  'frais-bancaires': [
    'frais mensuels',
    'frais de transaction',
    'interets',
    'frais de retrait',
    'frais hors reseau',
    'frais de releve',
    'frais de carte',
    'interets sur solde',
    'frais de depassement',
  ],
  impots: [],
  'autre-depense': [
    'frais de port',
    'frais de manutention',
    'frais environnementaux',
    'ecofrais',
    'frais de recyclage',
    'consigne canette',
    'depot de bouteille',
    'frais de sac',
    'sac de plastique',
    'carte prepayee',
    'timbre',
    'timbres',
    'enveloppe',
    'colis',
    'envoi',
    'photocopie',
    'plastification',
    'cle taillee',
    'pile bouton',
    'ampoule speciale',
    'papeterie diverse',
  ],
}
