import type { SousCategorie } from '@alambic/noyau'

// Les marchands, enseignes et termes qui trahissent la nature d'une depense. Repris du
// catalogue de YieldMomo (packages/shared/src/dashboard/categories-mots-cles.ts), qui les
// tient a jour pour sa recherche : les cles sont les memes, ce sont ses CategorieTransaction.
//
// Format, herite de la source : tout est deja normalise — minuscules, sans accents, espaces
// simples. Le reconnaisseur normalise le texte du recu de la meme facon avant de comparer.
//
// Ce qui differe de la source, et pourquoi : la-bas un humain tranche l'ambiguite en cliquant,
// ici personne ne tranche. Les categories de revenu sont donc absentes du noyau et de cette
// table, et deux familles de mots-cles ont ete retirees — ceux qui ne s'impriment que sur un
// releve bancaire, et ceux qu'une ligne d'entete de ticket peut porter sans nommer le
// commerce. Chaque retrait est
// justifie sur la categorie concernee ; une liste vide dit qu'aucun mot-cle ne survit au
// contexte du recu.
//
// Les collisions volontaires de la source sont en revanche conservees : « tim hortons » vaut
// restaurant ET cafe, « costco » vaut epicerie ET essence. C'est au reconnaisseur d'en tirer
// un refus de trancher, pas a cette table de choisir a sa place.
//
// Le Record force l'exhaustivite : une sous-categorie ajoutee au noyau casse la compilation
// ici tant qu'elle n'a pas ses mots-cles, fut-ce une liste vide.
export const MOTS_CLES: Record<SousCategorie, readonly string[]> = {
  // logement
  loyer: [
    'loyer',
    'proprietaire',
    'bail',
    'appartement',
    'logement',
    'gestion immobiliere',
    'habitations',
    'colocation',
    'proprio',
    'logement locatif',
    'immeubles',
    'immobilier locatif',
    'cogir',
    'akelius',
    'capreit',
    'residence pour aines',
    'chartwell',
    'sous-location',
    'loyer mensuel',
    'bail commercial',
    'espace locatif',
  ],
  hypotheque: [
    'hypotheque',
    'pret hypothecaire',
    'versement hypothecaire',
    'hypothecaire',
    'multi-prets',
    'multi prets',
    'nesto',
    'first national',
    'mcap',
    'renouvellement hypothecaire',
    'banque nationale hypotheque',
    'desjardins hypotheque',
    'scotia hypotheque',
    'bmo hypotheque',
    'cibc hypotheque',
    'rbc hypotheque',
    'td hypotheque',
    'true north',
    'pret immobilier',
    'assurance pret hypothecaire',
    'schl',
    'courtier hypothecaire',
    'planiprêt',
    'planipret',
    'multi-prets hypotheques',
  ],
  'assurance-habitation': [
    'assurance habitation',
    'assurance maison',
    'assurance logement',
    'assurance locataire',
    'intact',
    'beneva',
    'la capitale',
    'promutuel',
    'belairdirect',
    'belair direct',
    'desjardins assurances',
    'industrielle alliance',
    'allstate',
    'sonnet',
    'square one',
    'aviva',
    'wawanesa',
    'economical',
    'td assurance',
    'meloche monnex',
    'les cooperateurs',
    'cooperateurs',
    'assurance copropriete',
    'assurance condo',
    'assurance des particuliers',
    'unica',
    'northbridge',
    'lussier',
    'dale parizeau',
    'essor assurances',
    'ssq assurance',
    'ssq',
    'la personnelle',
    'personnelle assurance',
    'prime d assurance habitation',
  ],
  electricite: [
    'electricite',
    'hydro-quebec',
    'hydro quebec',
    'hydro',
    'hydro-sherbrooke',
    'hydro sherbrooke',
    'hydro westmount',
    'facture hydro',
    'hydro-joliette',
    'hydro joliette',
    'hydro-magog',
    'hydro magog',
    'hydro-coaticook',
    'coop d electricite',
    'releve de consommation',
    'kwh',
    'kilowattheure',
    'borne de recharge',
    'flo',
    'circuit electrique',
    'chargepoint',
  ],
  chauffage: [
    'chauffage',
    'energir',
    'gaz metro',
    'gaz naturel',
    'mazout',
    'propane',
    'huile a chauffage',
    'bois de chauffage',
    'superieur propane',
    'suncor propane',
    'granules de bois',
    'gaz propane',
    'propane levac',
    'levac',
    'budget propane',
    'filgaz',
    'sonic mazout',
    'mazout sonic',
    'chauffage au bois',
    'poele a bois',
    'fournaise',
    'plancher chauffant',
    'granules energex',
    'energex',
  ],
  'entretien-maison': [
    'entretien et reparations',
    'renovation',
    'reno-depot',
    'reno depot',
    'rona',
    'home depot',
    'canac',
    'bmr',
    'home hardware',
    'patrick morin',
    'quincaillerie',
    'plombier',
    'electricien',
    'peinture',
    'deneigement',
    'paysagement',
    'gazon',
    'piscine',
    'ramonage',
    'exterminateur',
    'serrurier',
    'toiture',
    'couvreur',
    'entrepreneur general',
    'climatisation',
    'thermopompe',
    'chauffagiste',
    'inspection en batiment',
    'alarme securite',
    'entretien menager',
    'femme de menage',
    'nettoyage',
    'lowes',
    'lowe s',
    'materiaux',
    'centre de renovation',
    'ace hardware',
    'matco',
    'groupe bmr',
    'agrizone',
    'plomberie',
    'menuisier',
    'renovation cuisine',
    'armoires de cuisine',
    'comptoir de cuisine',
    'nettoyage de conduits',
    'service de menage',
    'menage',
    'lavage de vitres',
    'emondage',
    'arboriculture',
    'pelouse',
    'weed man',
    'nutrite',
    'entretien paysager',
    'deneigement residentiel',
    'fosse septique',
    'vidange de fosse',
    'ramoneur',
    'frais de condo',
    'syndicat de copropriete',
    'gestion de copropriete',
    'arpenteur',
    'excavation',
    'asphaltage',
    'pavage',
    'unipierre',
    'vitrerie',
    'fenetres',
    'portes et fenetres',
    'solaris',
    'vertica',
    'gentek',
    'climatisation service',
    'ramonage de cheminee',
    'puits',
    'traitement d eau',
    'culligan',
    'adoucisseur',
    'outillage',
    'location d outils',
    'location d outillage',
    'simplex',
    'cash location',
    'hertz equipement',
    'battery direct',
    'quincaillerie richelieu',
  ],
  'meubles-deco': [
    'meubles et deco',
    'ikea',
    'structube',
    'brault et martineau',
    'brault martineau',
    'meubles leon',
    'leons',
    'mobilia',
    'economax',
    'ameublement',
    'homesense',
    'bouclair',
    'linen chest',
    'jysk',
    'wayfair',
    'decoration',
    'meuble',
    'matelas',
    'dormez-vous',
    'dormez vous',
    'sleep country',
    'tanguay',
    'meubles tanguay',
    'urban barn',
    'maison corbeil',
    'corbeil',
    'eq3',
    'zone maison',
    'stokes',
    'pier 1',
    'cb2',
    'crate and barrel',
    'must societe',
    'amnon',
    'jc perreault',
    'meubles rd',
    'meubles bmtc',
    'bmtc',
    'the brick',
    'ashley',
    'ameublement bilodeau',
    'matelas bonheur',
    'sommex',
    'obasan',
    'casper',
    'endy',
    'ikea suede',
    'articles de maison',
    'maison et deco',
    'encadrement',
    'rideaux et stores',
    'stores maison',
    'eclairage',
    'luminaire boutique',
    'multi luminaire',
    'vitrerie decorative',
    'tapis et moquette',
    'couvre-plancher',
    'couvre plancher',
    'planchers',
    'boutique deco',
    'simons maison',
    'at home',
    'home outfitters',
    'solutions rangement',
  ],

  // telecom
  internet: [
    'internet',
    'videotron',
    'bell',
    'telus',
    'rogers',
    'ebox',
    'oxio',
    'cogeco',
    'distributel',
    'teksavvy',
    'fibe',
    'helix',
    'wifi',
    'fournisseur internet',
    'xittel',
    'vmedia',
    'acanac',
    'starlink',
    'beanfield',
    'colba',
    'electronic box',
    'shaw',
    'eastlink',
    'internet residentiel',
    'forfait internet',
    'modem',
    'routeur',
    'installation internet',
    'fibre optique',
    'fibre',
  ],
  // Sans « telephone » : tout recu imprime son numero sous ce mot.
  cellulaire: [
    'cellulaire',
    'fizz',
    'koodo',
    'virgin plus',
    'virgin',
    'freedom mobile',
    'freedom',
    'public mobile',
    'chatr',
    'lucky mobile',
    'bell mobilite',
    'telus mobilite',
    'rogers',
    'videotron mobile',
    'forfait mobile',
    'recharge prepayee',
    'carte sim',
    'sim card',
    'telephone cellulaire',
    'forfait cellulaire',
    'chatr mobile',
    'petro-canada mobilite',
    'mobilite',
    'telephone mobile',
    'recharge cellulaire',
    'data mobile',
    'itinerance',
    'roaming',
    'sim prepayee',
    'telephone intelligent',
    'boutique telus',
    'boutique bell',
    'boutique videotron',
    'wireless',
  ],

  // alimentation
  epicerie: [
    'epicerie',
    'metro',
    'iga',
    'maxi',
    'super c',
    'provigo',
    'loblaws',
    'costco',
    'walmart',
    'adonis',
    'avril',
    'rachelle-bery',
    'rachelle bery',
    'marche richelieu',
    'bonichoix',
    'tradition',
    'intermarche',
    'supermarche',
    'marche',
    'fruiterie',
    'boucherie',
    'boulangerie',
    'poissonnerie',
    'depanneur',
    'aliments',
    'nourriture',
    'iga extra',
    'marche public',
    'epicerie fine',
    'iga express',
    'metro plus',
    'maxi et cie',
    'provigo le marche',
    'loblaw',
    'real canadian superstore',
    'superstore',
    'wholesale club',
    'club entrepot',
    'sobeys',
    'safeway',
    'freshco',
    'fresh co',
    'no frills',
    'food basics',
    'farm boy',
    'longos',
    'whole foods',
    'marche ami',
    'axep',
    'boni-soir',
    'boni soir',
    'voisin',
    'marche omni',
    'marche express',
    'marche adonis',
    'kim phat',
    'marche c&t',
    't&t',
    'marche oriental',
    'hawai supermarche',
    'sami fruits',
    'fruiterie 440',
    'marche 440',
    'supermarche pa',
    'marche pa',
    'marche atwater',
    'marche jean-talon',
    'marche jean talon',
    'segal',
    'bulk barn',
    'tau',
    'avril supermarche',
    'panier sante',
    'aliments naturels',
    'marche de l ouest',
    'premiere moisson',
    'au pain dore',
    'boulangerie artisanale',
    'patisserie',
    'chocolaterie',
    'fromagerie',
    'cremerie',
    'miellerie',
    'erabliere',
    'cabane a sucre',
    'poissonnerie du marche',
    'boucherie de campagne',
    'abattoir',
    'vergers',
    'autocueillette',
    'kiosque maraicher',
    'marche fermier',
    'ferme',
    'cooperative alimentaire',
    'coop alimentaire',
    'epicerie en ligne',
    'instacart',
    'marche goodfood',
    'voila',
    'grocery',
    'supermarket',
    'produce',
  ],
  restaurant: [
    'restaurant',
    'mcdo',
    'mcdonald',
    'mcdonalds',
    'tim hortons',
    'tims',
    'st-hubert',
    'st hubert',
    'la cage',
    'cage aux sports',
    'normandin',
    'chez ashton',
    'ashton',
    'subway',
    'a&w',
    'harveys',
    'wendys',
    'burger king',
    'pfk',
    'kfc',
    'valentine',
    'benny',
    'la belle province',
    'belle province',
    'boston pizza',
    'pacini',
    'scores',
    'mikes',
    'chez cora',
    'allo mon coco',
    'eggspectation',
    'thai express',
    'sushi shop',
    'sushi',
    'pizzeria',
    'pizza',
    'resto',
    'bistro',
    'brasserie',
    'casse-croute',
    'casse croute',
    'poutine',
    'tacos',
    'poke bowl',
    'shawarma',
    'cantine',
    'traiteur',
    'buffet',
    'delicatessen',
    'smoked meat',
    'creperie',
    'brunch',
    'st-hubert express',
    'rotisserie',
    'baton rouge',
    'houston',
    'bar b barn',
    'east side marios',
    'east side mario',
    'swiss chalet',
    'montanas',
    'the keg',
    'keg',
    'moxies',
    'earls',
    'milestones',
    'jack astor',
    '3 brasseurs',
    'les 3 brasseurs',
    'trois brasseurs',
    'archibald',
    'dairy queen',
    'popeyes',
    'five guys',
    'taco bell',
    'chipotle',
    'copper branch',
    'mandys',
    'lola rosa',
    'basha',
    'amir',
    'boustan',
    'nickels',
    'deli',
    'schwartz',
    'lafleur',
    'patati patata',
    'frite alors',
    'frites alors',
    'tousignant',
    'dic anns',
    'pizza hut',
    'domino',
    'dominos',
    'pizza pizza',
    'pizza salvatore',
    'salvatore',
    'double pizza',
    'no 900',
    'papa johns',
    'little caesars',
    'sushi taxi',
    'sushi sama',
    'odaki',
    'kanda',
    'mikado',
    'izakaya',
    'ramen',
    'banh mi',
    'thaizone',
    'thai zone',
    'vua',
    'wok',
    'teriyaki',
    'ma poule mouillee',
    'portugalia',
    'romados',
    'rotisserie portugaise',
    'marrakech',
    'tandoori',
    'india beau village',
    'cuisine indienne',
    'grec',
    'cuisine italienne',
    'trattoria',
    'osteria',
    'steakhouse',
    'grill',
    'pub',
    'taverne',
    'resto-bar',
    'resto bar',
    'cafeteria',
    'food court',
    'aire de restauration',
    'comptoir lunch',
    'snack bar',
    'casse-croute du village',
    'roulotte a patates',
    'food truck',
    'camion de rue',
    'chez ti-coq',
    'benny&co',
    'benny co',
    'rotisserie coq',
    'coq roti',
    'poulet frit kentucky',
    'restaurant chinois',
    'buffet chinois',
    'resto asiatique',
    'brasserie artisanale',
    'bistro-bar',
    'diner',
    'restaurant familial',
  ],
  // Sans « livraison », qui est une ligne de frais sur n'importe quel recu, ni « skip »,
  // trop court pour valoir preuve.
  'livraison-repas': [
    'livraison de repas',
    'uber eats',
    'ubereats',
    'doordash',
    'door dash',
    'skip the dishes',
    'skipthedishes',
    'fantuan',
    'goodfood',
    'hellofresh',
    'cook it',
    'dashpass',
    'ritual',
    'foodora',
    'chefs plate',
    'marche fraiche',
    'miam',
    'allo resto',
    'delivro',
    'livraison a domicile',
    'commande en ligne repas',
    'chef a la maison',
    'boite repas',
    'pret a manger livre',
  ],
  cafe: [
    'cafe',
    'starbucks',
    'second cup',
    'presse cafe',
    'cafe depot',
    'van houtte',
    'brulerie',
    'mccafe',
    'tim hortons',
    'nespresso',
    'keurig',
    'torrefaction',
    'java u',
    'pilon',
    'dunkin',
    'cafe william',
    'faro',
    'pikolo',
    'crew collective',
    'myriade',
    'saint-henri',
    'st-henri',
    'olimpico',
    'cafe olimpico',
    'tommy',
    'dispatch',
    'brulerie st-denis',
    'cafe union',
    'barista',
    'cafe de la rue',
    'torrefacteur',
    'coffee',
    'coffee shop',
    'espresso bar',
    'tim horton',
    'starbucks reserve',
    'mccafe drive',
    'cafe bistro',
    'salon de the',
    'maison de the',
    'davids tea',
    'teavana',
    'bubble tea',
    'the bulles',
    'chatime',
    'cha time',
  ],
  alcool: [
    'alcool',
    'saq',
    'lcbo',
    'biere',
    'vin',
    'spiritueux',
    'microbrasserie',
    'vignoble',
    'cidrerie',
    'distillerie',
    'boisson alcoolisee',
    'bar a vin',
    'succursale saq',
    'saq express',
    'saq depot',
    'saq selection',
    'saq signature',
    'societe des alcools',
    'societe des alcools du quebec',
    'depanneur biere',
    'broue pub',
    'pub brasseur',
    'la barberie',
    'dieu du ciel',
    'trou du diable',
    'pit caribou',
    'farnham ale',
    'noctem',
    'vices et versa',
    'brasseur de montreal',
    'brasserie artisanale du quebec',
    'boutique de vin',
    'importation privee',
    'agence de vin',
    'caviste',
    'spiritueux artisanaux',
    'hydromel',
    'meaderie',
    'liquor',
    'liquor store',
    'beer store',
    'wine',
  ],

  // transport
  vehicule: [
    'paiement du vehicule',
    'pret auto',
    'financement auto',
    'mensualite auto',
    'location long terme',
    'lease',
    'concessionnaire',
    'saaq',
    'immatriculation',
    'permis de conduire',
    'credit auto',
    'leasing',
    'hgregoire',
    'h gregoire',
    'lallier',
    'spinelli',
    'park avenue',
    'john scotti',
    'automobiles',
    'vente d automobiles',
    'auto neuve',
    'auto usagee',
    'concession automobile',
    'location de vehicule long terme',
    'credit-bail',
    'credit bail',
    'solde de financement',
    'pret automobile',
    'transfert de propriete',
    'droit d immatriculation',
    'plaque d immatriculation',
    'renouvellement de permis',
    'moto',
    'vtt',
    'motoneige',
    'roulotte',
    'bateau',
  ],
  essence: [
    'essence',
    'petro-canada',
    'petro canada',
    'petro-t',
    'petro t',
    'esso',
    'shell',
    'ultramar',
    'couche-tard',
    'couche tard',
    'irving',
    'crevier',
    'harnois',
    'mobil',
    'costco essence',
    'station-service',
    'station service',
    'carburant',
    'diesel',
    'pompe a essence',
    'valero',
    'circle k',
    'olco',
    'sonic',
    'coop essence',
    'mcewen',
    'pioneer',
    'husky',
    'flying j',
    'chevron',
    'gulf',
    'north atlantic',
    'petro pass',
    'esso on the run',
    'on the run',
    'shell select',
    'depanneur essence',
    'libre-service essence',
    'libre service',
    'carte carburant',
    'poste d essence',
    'gaz bar',
    'gasoline',
    'gas station',
    'fuel stop',
  ],
  'assurance-auto': [
    'assurance auto',
    'assurance vehicule',
    'assurance automobile',
    'intact',
    'beneva',
    'belairdirect',
    'belair direct',
    'la capitale',
    'promutuel',
    'desjardins assurances',
    'industrielle alliance',
    'allstate',
    'sonnet',
    'aviva',
    'wawanesa',
    'economical',
    'td assurance',
    'meloche monnex',
    'assurance moto',
    'assurance vr',
    'prime d assurance auto',
    'ssq auto',
    'la personnelle auto',
    'unique assurances',
    'pafco',
    'coseco',
    'optimum assurance',
    'lussier dale parizeau',
    'courtier en assurance',
    'contribution d assurance saaq',
    'avenant',
  ],
  'entretien-vehicule': [
    'entretien du vehicule',
    'garage',
    'mecanicien',
    'changement d huile',
    'vidange d huile',
    'pneus',
    'pneu',
    'canadian tire',
    'mr lube',
    'monsieur muffler',
    'midas',
    'napa',
    'lave-auto',
    'lave auto',
    'carrosserie',
    'silencieux',
    'freins',
    'antirouille',
    'krown',
    'docteur du pare-brise',
    'pare-brise',
    'pare brise',
    'batterie auto',
    'remorquage',
    'transmission',
    'speedy',
    'point s',
    'uni-select',
    'uni select',
    'partsource',
    'part source',
    'carquest',
    'bumper to bumper',
    'pieces d auto',
    'centre du pneu',
    'centre de l auto',
    'atelier mecanique',
    'fix auto',
    'carstar',
    'boyd',
    'novus',
    'speedy glass',
    'vitrerie d auto',
    'esthetique automobile',
    'traitement antirouille',
    'garage bosch',
    'service auto',
    'atelier de mecanique',
    'inspection mecanique',
    'toyota service',
    'honda service',
    'ford service',
    'pieces et accessoires',
    'auto value',
    'tirecraft',
    'tire craft',
    'pneus ratte',
    'maxi pneus',
    'sos remorquage',
    'cai remorquage',
    'cireur auto',
  ],
  stationnement: [
    'stationnement',
    'parking',
    'parcometre',
    'horodateur',
    'indigo',
    'impark',
    'stationnement de montreal',
    'stationnement souterrain',
    'stationnement de quebec',
    'stationnement ville',
    'precise parklink',
    'parkwhiz',
    'stationnement aeroport',
    'vignette de stationnement',
    'borne de paiement',
    'espace stationnement',
    'parc-o-bus',
    'parc o bus',
    'garage municipal',
    'stationnement mensuel',
    'parking lot',
  ],
  'transport-commun': [
    'transport en commun',
    'stm',
    'rtc',
    'stl',
    'rtl',
    'exo',
    'opus',
    'autobus',
    'metro de montreal',
    'train',
    'via rail',
    'orleans express',
    'bixi',
    'transport adapte',
    'presto',
    'sto',
    'sts',
    'stsaguenay',
    'societe de transport',
    'amt',
    'reseau express metropolitain',
    'megabus',
    'intercar',
    'limocar',
    'autocar',
    'keolis',
    'taxibus',
    'navette aeroport',
    'titre mensuel',
    'carte opus',
    'recharge opus',
  ],
  taxi: [
    'taxi et covoiturage',
    'uber',
    'eva',
    'taxi coop',
    'taxi diamond',
    'covoiturage',
    'communauto',
    'teo taxi',
    'lyft',
    'coop taxi',
    'taxi bonjour',
    'taxi para-adapte',
    'taxi hochelaga',
    'taxi 5000',
    'taxi de quebec',
    'bond taxi',
    'ride share',
    'course uber',
    'eva coop',
  ],

  // sante
  medicaments: [
    'medicaments',
    'jean coutu',
    'pharmaprix',
    'uniprix',
    'familiprix',
    'brunet',
    'proxim',
    'acces pharma',
    'pharmacie',
    'prescription',
    'ordonnance',
    'vaccin',
    'shoppers',
    'shoppers drug mart',
    'pharmasave',
    'rexall',
    'london drugs',
    'pharmachoice',
    'pharmacie du village',
    'costco pharmacie',
    'walmart pharmacie',
    'pharmacie familiale',
    'medicament d ordonnance',
    'renouvellement d ordonnance',
    'pilulier',
    'pharmacien',
    'drug mart',
    'pharmacy',
  ],
  // Sans « urgence », qui s'imprime sur des recus n'ayant rien de medical.
  'soins-medicaux': [
    'soins medicaux',
    'clinique',
    'medecin',
    'physiotherapie',
    'physio',
    'chiropraticien',
    'chiro',
    'osteopathe',
    'osteo',
    'massotherapie',
    'massage',
    'optometriste',
    'lunettes',
    'lunetterie',
    'new look',
    'iris',
    'greiche scaff',
    'psychologue',
    'therapie',
    'acupuncture',
    'podiatre',
    'laboratoire',
    'prise de sang',
    'biron',
    'ramq',
    'ergotherapie',
    'nutritionniste',
    'dietetiste',
    'audiologiste',
    'orthophoniste',
    'sage-femme',
    'sage femme',
    'clinique medicale',
    'sans rendez-vous',
    'hopital',
    'chsld',
    'clinique privee',
    'lasik md',
    'lasik',
    'ophtalmologie',
    'audioprothesiste',
    'lobe',
    'clinique auditive',
    'dermatologue',
    'telemedecine',
    'maple',
    'imagerie medicale',
    'radiologie',
    'echographie',
    'irm',
    'clsc',
    'physio extra',
    'action sport physio',
    'kinesiologue',
    'naturopathe',
    'sexologue',
    'travailleur social',
    'psychotherapie',
    'psychiatre',
    'clinique de fertilite',
    'vaccination voyage',
    'clinique du voyageur',
    'orthesiste',
    'orthese',
    'prothese',
    'medical',
    'clinic',
  ],
  dentiste: [
    'dentiste',
    'dentaire',
    'clinique dentaire',
    'orthodontiste',
    'hygieniste',
    'nettoyage dentaire',
    'broches',
    'invisalign',
    'couronne dentaire',
    'extraction dentaire',
    'plombage',
    'centre dentaire',
    'denturologiste',
    'denturologie',
    'endodontiste',
    'parodontiste',
    'implant dentaire',
    'clinique d orthodontie',
    'dentalcorp',
    'soins dentaires',
    'prothese dentaire',
    'blanchiment dentaire',
    'dental',
    'dentiste familial',
  ],
  sport: [
    'sport et gym',
    'gym',
    'econofitness',
    'econo fitness',
    'nautilus',
    'energie cardio',
    'world gym',
    'goodlife',
    'fitness',
    'entrainement',
    'yoga',
    'crossfit',
    'natation',
    'hockey',
    'soccer',
    'golf',
    'tennis',
    'escalade',
    'centre de ski',
    'ski alpin',
    'abonnement gym',
    'club de golf',
    'centre sportif',
    'velo',
    'patinoire',
    'karate',
    'arts martiaux',
    'ymca',
    'nautilus plus',
    'buzz fitness',
    'orangetheory',
    'f45',
    'anytime fitness',
    'planet fitness',
    'carrefour multisports',
    'studio de yoga',
    'pilates',
    'spinning',
    'boxe',
    'judo',
    'taekwondo',
    'gymnastique',
    'arena',
    'aréna',
    'centre aquatique',
    'piscine municipale',
    'club de course',
    'ligue de garage',
    'tournoi',
    'mont tremblant',
    'bromont',
    'saint-sauveur',
    'sommet',
    'stoneham',
    'le massif',
    'le relais',
    'vallee du parc',
    'owl s head',
    'ski de fond',
    'raquette',
    'camp d entrainement',
    'club sportif',
    'terrain de golf',
    'practice de golf',
    'quilles sport',
    'curling',
    'badminton',
    'squash',
    'escrime',
    'athletisme',
    'triathlon',
    'marathon',
    'inscription course',
    'dossard',
  ],

  // personnel
  vetements: [
    'vetements',
    'simons',
    'la baie',
    'winners',
    'h&m',
    'zara',
    'uniqlo',
    'old navy',
    'gap',
    'shein',
    'sports experts',
    'aubainerie',
    'ardene',
    'reitmans',
    'rw&co',
    'dynamite',
    'lululemon',
    'nike',
    'adidas',
    'foot locker',
    'browns',
    'aldo',
    'chaussures',
    'souliers',
    'bottes',
    'manteau',
    'linge',
    'boutique',
    'friperie',
    'village des valeurs',
    'moores',
    'tristan',
    'sail',
    'atmosphere',
    'decathlon',
    'urban outfitters',
    'american eagle',
    'marks',
    'mark s',
    'l equipeur',
    'sportium',
    'sports rousseau',
    'ssense',
    'frank and oak',
    'frank oak',
    'bikini village',
    'la vie en rose',
    'la senza',
    'roots',
    'canada goose',
    'columbia',
    'north face',
    'under armour',
    'puma',
    'new balance',
    'vans',
    'converse',
    'skechers',
    'globo',
    'chaussures pop',
    'little burgundy',
    'call it spring',
    'bentley',
    'pandora',
    'swarovski',
    'michael kors',
    'marshalls',
    'psyche',
    'boutique de vetements',
    'pret a porter',
    'mode',
    'vetements pour enfants',
    'carters',
    'childrens place',
    'gymboree',
    'souris mini',
    'deux par deux',
    'orchestra',
    'boutique bebe',
    'bonneterie',
    'cordonnerie',
    'retouches',
    'couturiere',
    'nettoyeur',
    'buanderie',
    'clothing',
    'apparel',
    'shoes',
  ],
  'soins-personnels': [
    'coiffure et soins',
    'coiffeur',
    'salon de coiffure',
    'barbier',
    'barber shop',
    'esthetique',
    'estheticienne',
    'manucure',
    'pedicure',
    'ongles',
    'epilation',
    'spa detente',
    'strom',
    'bota bota',
    'scandinave',
    'sephora',
    'produits de beaute',
    'cosmetiques',
    'maquillage',
    'lush',
    'rasage',
    'yves rocher',
    'tatouage',
    'piercing',
    'parfumerie',
    'the body shop',
    'body shop',
    'bath and body works',
    'ulta',
    'marcelle',
    'nail bar',
    'salon d ongles',
    'spa nordique',
    'balnea',
    'ofuro',
    'sky spa',
    'institut de beaute',
    'centre d epilation',
    'epilation au laser',
    'electrolyse',
    'magicuts',
    'great clips',
    'first choice',
    'tchip',
    'coiffure',
    'salon de beaute',
    'microblading',
    'extensions de cils',
    'pose d ongles',
    'bronzage',
    'salon de bronzage',
    'soins du visage',
    'produits capillaires',
    'beaute',
    'hair salon',
    'nails',
    'spa',
  ],

  // loisirs
  streaming: [
    'abonnements et streaming',
    'netflix',
    'spotify',
    'disney plus',
    'disney',
    'crave',
    'prime video',
    'amazon prime',
    'apple tv',
    'apple music',
    'icloud',
    'youtube premium',
    'hbo',
    'paramount',
    'illico',
    'club illico',
    'tou tv',
    'deezer',
    'twitch',
    'patreon',
    'google one',
    'microsoft 365',
    'office 365',
    'dropbox',
    'chatgpt',
    'openai',
    'canva',
    'tva plus',
    'noovo',
    'adobe',
    'creative cloud',
    'peacock',
    'discovery plus',
    'britbox',
    'crunchyroll',
    'mubi',
    'shudder',
    'plex',
    'tidal',
    'soundcloud',
    'vimeo',
    'substack',
    'notion',
    'slack',
    'zoom',
    'github',
    'onedrive',
    'google drive',
    'nordvpn',
    'nord vpn',
    'express vpn',
    '1password',
    'lastpass',
    'anthropic',
    'claude ai',
    'midjourney',
    'sirius xm',
    'siriusxm',
    'audible abonnement',
    'apple one',
    'amazon music',
    'hulu',
    'starz',
    'super ecran',
    'abonnement mensuel numerique',
    'abonnement annuel',
    'subscription',
    'renouvellement automatique',
  ],
  'jeux-video': [
    'jeux video',
    'steam',
    'playstation',
    'ps plus',
    'xbox',
    'game pass',
    'nintendo',
    'nintendo eshop',
    'eb games',
    'gamestop',
    'epic games',
    'blizzard',
    'ea play',
    'riot',
    'app store',
    'google play',
    'playstation network',
    'ubisoft',
    'oculus',
    'meta quest',
    'humble bundle',
    'gog',
    'itch io',
    'battle net',
    'battlenet',
    'origin',
    'rockstar',
    'square enix',
    'bandai',
    'capcom',
    'microsoft store',
    'nintendo store',
    'microplay',
    'level up',
    'retro gaming',
    'jeux usages',
    'console de jeu',
    'manette de jeu',
    'carte prepayee jeux',
    'psn',
    'eshop',
    'steam wallet',
    'gaming',
    'esport',
  ],
  sorties: [
    'sorties et spectacles',
    'cinema',
    'cineplex',
    'guzzo',
    'spectacle',
    'concert',
    'billet',
    'ticketmaster',
    'evenko',
    'theatre',
    'musee',
    'la ronde',
    'osheaga',
    'festival',
    'quilles',
    'billard',
    'escape room',
    'arcade',
    'karaoke',
    'place des arts',
    'juste pour rire',
    'aquarium',
    'zoo',
    'jardin botanique',
    'bowling',
    'patinage',
    'cineplex odeon',
    'cinema banque scotia',
    'cinema beaubien',
    'cinema du parc',
    'starcite',
    'imax',
    'cineplex vip',
    'theatre st-denis',
    'mtelus',
    'centre bell',
    'centre videotron',
    'place bell',
    'opera de montreal',
    'orchestre symphonique',
    'osm',
    'francofolies',
    'festival de jazz',
    'grand prix',
    'cf montreal',
    'canadiens',
    'alouettes',
    'rocket de laval',
    'remparts',
    'biodome',
    'planetarium',
    'insectarium',
    'centre des sciences',
    'pointe-a-calliere',
    'musee des beaux-arts',
    'valcartier',
    'village vacances',
    'super aqua club',
    'zoo de granby',
    'parc omega',
    'laser tag',
    'trampoline park',
    'isaute',
    'clip n climb',
    'minigolf',
    'mini-golf',
    'karting',
    'go kart',
    'salle de spectacle',
    'boite a chanson',
    'discotheque',
    'club de nuit',
    'soiree',
    'billetterie',
    'lepointdevente',
    'tickets',
  ],
  lecture: [
    'livres et lecture',
    'renaud-bray',
    'renaud bray',
    'archambault',
    'indigo',
    'chapters',
    'librairie',
    'livre',
    'bouquin',
    'kindle',
    'kobo',
    'audible',
    'bibliotheque',
    'magazine',
    'le devoir',
    'journal',
    'abonnement magazine',
    'la presse',
    'librairie monet',
    'librairie gallimard',
    'librairie raffin',
    'raffin',
    'buropro',
    'coles',
    'les libraires',
    'leslibraires',
    'bande dessinee',
    'presse plus',
    'l actualite',
    'protegez-vous',
    'national geographic',
    'the gazette',
    'le soleil',
    'le droit',
    'journal de montreal',
    'journal de quebec',
    'abonnement journal',
    'librairie d occasion',
    'livres usages',
    'papeterie',
    'book',
    'bookstore',
    'library',
  ],
  // Sans « avis », mot courant d'un recu avant d'etre un loueur de voitures.
  voyages: [
    'voyages',
    'air canada',
    'air transat',
    'transat',
    'sunwing',
    'porter',
    'westjet',
    'flair',
    'expedia',
    'booking',
    'airbnb',
    'hotel',
    'motel',
    'auberge',
    'billet d avion',
    'croisiere',
    'agence de voyage',
    'aeroport',
    'passeport',
    'enterprise',
    'hertz',
    'location de voiture',
    'greyhound',
    'auberge de jeunesse',
    'location de chalet',
    'flixbus',
    'camping',
    'parc national',
    'sepaq',
    'hotels com',
    'trivago',
    'kayak',
    'vrbo',
    'marriott',
    'hilton',
    'holiday inn',
    'best western',
    'fairmont',
    'sheraton',
    'delta hotels',
    'comfort inn',
    'super 8',
    'travelodge',
    'quality inn',
    'hampton inn',
    'chateau frontenac',
    'gite',
    'pourvoirie',
    'air france',
    'klm',
    'lufthansa',
    'british airways',
    'united airlines',
    'american airlines',
    'jetblue',
    'southwest',
    'copa',
    'aeromexico',
    'swoop',
    'lynx air',
    'vacances air canada',
    'club med',
    'vacances transat',
    'aeroplan',
    'duty free',
    'boutique hors taxes',
    'voyages en groupe',
    'circuit touristique',
    'excursion',
    'visite guidee',
    'sepaq reservation',
    'camping quebec',
    'koa',
    'terrain de camping',
    'chalet a louer',
    'resort',
    'all inclusive',
    'tout inclus',
    'hostel',
    'travel',
    'airlines',
    'flight',
  ],

  // famille
  'garde-enfants': [
    'garderie',
    'cpe',
    'service de garde',
    'gardienne',
    'nounou',
    'camp de jour',
    'camp d ete',
    'halte-garderie',
    'halte garderie',
    'educatrice',
    'agence de gardiennage',
    'garderie educative',
    'milieu familial',
    'garderie privee',
    'service de garde scolaire',
    'camp musical',
    'camp de vacances',
    'camp specialise',
    'babysitter',
    'gardiennage',
    'cpe subventionne',
    'frais de garde journalier',
    'maternelle privee',
    'prematernelle',
    'daycare',
  ],
  animaux: [
    'animaux',
    'veterinaire',
    'animalerie',
    'mondou',
    'chico',
    'toilettage',
    'chien',
    'litiere',
    'croquettes',
    'nourriture pour chien',
    'pension pour animaux',
    'clinique veterinaire',
    'refuge animalier',
    'pattes et griffes',
    'pmc',
    'animal expert',
    'rens pets',
    'ren s pets',
    'petsmart',
    'pet smart',
    'petland',
    'global pet foods',
    'hopital veterinaire',
    'clinique animale',
    'spca',
    'sos animaux',
    'pension canine',
    'dressage canin',
    'garderie canine',
    'educateur canin',
    'toiletteur',
    'royal canin',
    'purina',
    'hills',
    'boutique pour animaux',
    'aquariophilie',
    'animalerie du coin',
    'chat',
    'chien et chat',
    'pet',
    'vet clinic',
  ],
  // Sans « emballage » : des frais d'emballage ne font pas un cadeau.
  'cadeaux-offerts': [
    'cadeaux offerts',
    'carte-cadeau',
    'carte cadeau',
    'anniversaire',
    'noel',
    'mariage',
    'bapteme',
    'baby shower',
    'fete des meres',
    'fete des peres',
    'fleuriste',
    'bouquet de fleurs',
    'livraison de fleurs',
    'ballons',
    'party expert',
    'articles de fete',
    'boutique cadeau',
    'cadeau souvenir',
    'panier cadeau',
    'gravure',
    'personnalisation',
    'shower',
    'faire-part',
    'liste de mariage',
    'gift',
    'gift card',
  ],
  dons: [
    'dons de charite',
    'centraide',
    'croix-rouge',
    'croix rouge',
    'unicef',
    'oxfam',
    'medecins sans frontieres',
    'fondation',
    'leucan',
    'moisson montreal',
    'guignolee',
    'eglise',
    'don mensuel',
    'telethon',
    'operation nez rouge',
    'banque alimentaire',
    'societe canadienne du cancer',
    'fondation du cancer',
    'sainte-justine',
    'chu sainte-justine',
    'shriners',
    'armee du salut',
    'jeunesse au soleil',
    'sun youth',
    'dystrophie musculaire',
    'coeur et avc',
    'diabete quebec',
    'wwf',
    'greenpeace',
    'amnistie internationale',
    'vision mondiale',
    'operation enfant soleil',
    'arbre de l espoir',
    'dons planifies',
    'campagne de financement',
    'collecte de fonds',
    'charite',
    'organisme de bienfaisance',
    'donation',
    'charity',
  ],

  // education
  scolarite: [
    'scolarite',
    'universite',
    'cegep',
    'college',
    'uqam',
    'udem',
    'mcgill',
    'concordia',
    'ulaval',
    'hec montreal',
    'polytechnique',
    'frais de scolarite',
    'droits de scolarite',
    'inscription scolaire',
    'ecole privee',
    'materiel scolaire',
    'residence etudiante',
    'frais afferents',
    'rentree scolaire',
    'fournitures scolaires',
    'universite laval',
    'uqtr',
    'uqac',
    'uqar',
    'uqo',
    'uqat',
    'ecole de technologie superieure',
    'enap',
    'teluq',
    'universite de sherbrooke',
    'bishop',
    'dawson',
    'vanier',
    'john abbott',
    'college ahuntsic',
    'college de maisonneuve',
    'college rosemont',
    'college montmorency',
    'edouard-montpetit',
    'lionel-groulx',
    'cegep garneau',
    'cegep limoilou',
    'cegep sainte-foy',
    'commission scolaire',
    'centre de services scolaire',
    'csdm',
    'cssdm',
    'ecole secondaire',
    'ecole primaire',
    'college prive',
    'brebeuf',
    'regina assumpta',
    'frais d inscription scolaire',
    'surveillance des midis',
    'sortie educative',
    'album des finissants',
    'uniforme scolaire',
    'tuition',
    'school',
  ],
  // Sans « cours » ni « atelier » : trop courants, et un atelier est aussi un garage.
  formation: [
    'formation',
    'udemy',
    'coursera',
    'linkedin learning',
    'masterclass',
    'formation en ligne',
    'certification',
    'seminaire',
    'webinaire',
    'duolingo',
    'skillshare',
    'pluralsight',
    'edx',
    'khan academy',
    'ecole de conduite',
    'tecnic',
    'ecole de langues',
    'alliance francaise',
    'berlitz',
    'bootcamp',
    'le wagon',
    'brainstation',
    'datacamp',
    'codecademy',
    'oreilly',
    'o reilly',
    'pmi',
    'certification pmp',
    'asp construction',
    'carte aces',
    'cours de secourisme',
    'rcr',
    'ambulance saint-jean',
    'cours de conduite',
    'permis probatoire',
    'cours prive',
    'tutorat',
    'professeur particulier',
    'cours de musique',
    'ecole de musique',
    'conservatoire',
    'cours de danse',
    'cours de langue',
    'training',
    'workshop',
  ],

  // finances
  // Un virement vers l'epargne ne se photographie pas non plus.
  epargne: [],
  // Un remboursement de dette est une ligne de releve, jamais une photo de recu. Ses
  // mots-cles de marque (« visa », « mastercard ») se declencheraient de surcroit sur le
  // pied de ticket de presque tous les terminaux.
  'remboursement-dette': [],
  // Sans les noms d'institutions : ils s'impriment dans le pied de ticket du terminal
  // (« DESJARDINS » sur un releve Interac) sans que le commerce soit une banque. Seuls les
  // libelles de frais restent. « guichet » seul est trop commun.
  'frais-bancaires': [
    'frais bancaires',
    'frais mensuels',
    'frais de service',
    'frais de guichet',
    'frais nsf',
    'frais de retard',
    'frais d interet',
    'frais annuel',
    'frais de change',
    'frais de conversion',
    'frais de decouvert',
    'frais de virement',
    'frais interac',
    'frais de guichet automatique',
    'frais d administration',
    'frais de tenue de compte',
    'frais de cheque',
    'frais de transfert',
    'frais de plan',
    'cotisation annuelle carte',
  ],
  impots: [
    'impots',
    'revenu quebec',
    'revenu canada',
    'agence du revenu',
    'cra',
    'impot federal',
    'impot provincial',
    'acomptes provisionnels',
    'taxes municipales',
    'taxe scolaire',
    'taxe de bienvenue',
    'solde d impot',
    'impot foncier',
    'declaration de revenus',
    'taxe fonciere',
    'taxes municipales annuelles',
    'mrc',
    'h&r block',
    'impotrapide',
    'turbo impot',
    'turboimpot',
    'ufile',
    'rapport d impot',
    'cotisation rrq',
    'cotisation rqap',
    'assurance emploi',
    'acompte provisionnel',
    'avis de cotisation',
    'remise de taxes',
    'tps tvq a remettre',
  ],

  // divers
  'autre-depense': [
    'dollarama',
    'amazon',
    'temu',
    'aliexpress',
    'ebay',
    'etsy',
    'best buy',
    'la source',
    'apple store',
    'bureau en gros',
    'staples',
    'paypal',
    'kijiji',
    'marketplace',
    'wish',
    'dollar tree',
    'magasin a un dollar',
    'giant tiger',
    'rossy',
    'hart',
    'postes canada',
    'poste canada',
    'purolator',
    'fedex',
    'ups',
    'dhl',
    'point de depot',
    'toys r us',
    'toysrus',
    'benjo',
    'l imaginaire',
    'club jouet',
    'jouets',
    'lego',
    'michaels',
    'deserres',
    'omer deserres',
    'club tissus',
    'fabricville',
    'vitrine sur l art',
    'photo service',
    'imprimerie',
    'vistaprint',
    'serrurier mobile',
    'consigne bouteilles',
    'friperie en ligne',
    'vente de garage',
    'marche aux puces',
    'boutique en ligne',
    'frais de douane',
    'frais d expedition',
    'livraison colis',
  ],
}
