import type { SousCategorie } from '@alambic/noyau'

// Les marchands, enseignes et termes qui trahissent la nature d'une depense. Partie du
// catalogue de YieldMomo (packages/shared/src/dashboard/categories-mots-cles.ts) : les cles de
// categorie sont les siennes, ce sont ses CategorieTransaction. Les mots-cles, eux, ont diverge
// — la table porte plus d'un millier d'enseignes et de termes de recu que la source n'a pas.
// Elle ne se resynchronise donc pas en ecrasant, seulement en reportant un ajout de la source.
//
// Format, herite de la source : tout est deja normalise — minuscules, sans accents, espaces
// simples. Le reconnaisseur normalise le texte du recu de la meme facon avant de comparer.
//
// Ce qui differe de la source, et pourquoi : la-bas un humain tranche l'ambiguite en cliquant,
// ici personne ne tranche. Les categories de revenu sont donc absentes du noyau et de cette
// table, et deux familles de mots-cles ont ete retirees — ceux qui ne s'impriment que sur un
// releve bancaire, et ceux qu'une ligne d'entete de ticket peut porter sans nommer le
// commerce. Chaque retrait est
// justifie sur la categorie concernee ; une liste vide dit qu'aucun mot-cle ne survit au
// contexte du recu.
//
// Les collisions volontaires de la source sont en revanche conservees : « tim hortons » vaut
// restaurant ET cafe, « indigo » vaut stationnement ET lecture. C'est au reconnaisseur d'en
// tirer un refus de trancher, pas a cette table de choisir a sa place.
//
// Le Record force l'exhaustivite : une sous-categorie ajoutee au noyau casse la compilation
// ici tant qu'elle n'a pas ses mots-cles, fut-ce une liste vide.
export const MOTS_CLES: Record<SousCategorie, readonly string[]> = {
  // logement
  loyer: [
    'loyer',
    'proprietaire',
    'bail',
    'appartement',
    'logement',
    'gestion immobiliere',
    'habitations',
    'colocation',
    'proprio',
    'logement locatif',
    'immeubles',
    'immobilier locatif',
    'cogir',
    'akelius',
    'capreit',
    'residence pour aines',
    'chartwell',
    'sous-location',
    'loyer mensuel',
    'bail commercial',
    'espace locatif',
    'loyer residentiel',
    'depot de garantie',
    'caution',
    'gestion locative',
    'immeuble a logements',
    'residence etudiante loyer',
    'chambre a louer',
    'studio a louer',
    'demi sous-sol',
    'quatre et demi',
    'cinq et demi',
    'trois et demi',
    'proprietaires unis',
    'regie du logement',
    'tribunal administratif du logement',
    'tal',
    'condo a louer',
    'sous-sol a louer',
    'agence de location',
    'residence pour etudiants',
    'coop d habitation',
    'cooperative d habitation',
    'habitations a loyer modique',
    'hlm',
    'loyer avril',
    'loyer mai',
    'loyer d avance',
    'colocataire',
    'bail de logement',
    'location d appartement',
    'proprietaire bailleur',
    'avis d augmentation de loyer',
    'loyer quatre et demi',
    'loyer trois et demi',
    'loyer cinq et demi',
    'condo locatif',
    'sous-locataire',
    'bail renouvelable',
    'societe immobiliere',
    'residence privee pour aines',
    'habitation a loyer modique',
    'office municipal d habitation',
    'logis quebec',
    'societe d habitation du quebec',
    'frais de bail',
    'depot damages',
  ],
  hypotheque: [
    'hypotheque',
    'pret hypothecaire',
    'versement hypothecaire',
    'hypothecaire',
    'multi-prets',
    'multi prets',
    'nesto',
    'first national',
    'mcap',
    'renouvellement hypothecaire',
    'banque nationale hypotheque',
    'desjardins hypotheque',
    'scotia hypotheque',
    'bmo hypotheque',
    'cibc hypotheque',
    'rbc hypotheque',
    'td hypotheque',
    'true north',
    'pret immobilier',
    'assurance pret hypothecaire',
    'schl',
    'courtier hypothecaire',
    'planipret',
    'multi-prets hypotheques',
    'butler mortgage',
    'dominion lending',
    'cmls',
    'radius financial',
    'street capital',
    'home trust',
    'equitable bank',
    'manuvie hypotheque',
    'manulife bank',
    'laurentienne hypotheque',
    'banque laurentienne hypotheque',
    'solidarite hypotheque',
    'caisse populaire hypotheque',
    'refinancement hypothecaire',
    'marge de credit hypothecaire',
    'preapprobation hypothecaire',
    'terme hypothecaire',
    'amortissement hypothecaire',
    'pret relais',
    'hypotheque inversee',
    'chip hypotheque inversee',
    'hypotheque a taux fixe',
    'hypotheque a taux variable',
    'homequity bank',
    'notaire hypotheque',
    'quittance hypothecaire',
    'radiation hypothecaire',
    'taux hypothecaire',
    'versement bimensuel hypotheque',
    'courtage hypothecaire',
    'hypotheque a renouveler',
    'solde hypothecaire',
  ],
  'assurance-habitation': [
    'assurance habitation',
    'assurance maison',
    'assurance logement',
    'assurance locataire',
    'intact',
    'beneva',
    'la capitale',
    'promutuel',
    'belairdirect',
    'belair direct',
    'desjardins assurances',
    'industrielle alliance',
    'allstate',
    'sonnet',
    'square one',
    'aviva',
    'wawanesa',
    'economical',
    'td assurance',
    'meloche monnex',
    'les cooperateurs',
    'cooperateurs',
    'assurance copropriete',
    'assurance condo',
    'assurance des particuliers',
    'unica',
    'northbridge',
    'lussier',
    'dale parizeau',
    'essor assurances',
    'ssq assurance',
    'ssq',
    'la personnelle',
    'personnelle assurance',
    'prime d assurance habitation',
    'desjardins agence',
    'chubb assurance',
    'travelers assurance',
    'co-operators',
    'assurance tenant',
    'assurance locative',
    'assurance proprietaire',
    'assurance multirisque',
    'assurance chalet',
    'assurance residence secondaire',
    'assurance immeuble a revenus',
    'gestion des risques assurance',
    'courtier d assurance',
    'jean campeau',
    'sirois assurances',
    'renouvellement assurance habitation',
    'prime annuelle habitation',
    'assurance proprietaire occupant',
    'assurance multirisque habitation',
    'garantie degat d eau',
    'avenant bijoux',
    'optimum assurance habitation',
    'mutuelle des municipalites',
    'polices d assurance habitation',
    'assureur habitation',
    'assurance copropriete divise',
    'assurance locataire chambre',
  ],
  electricite: [
    'electricite',
    'hydro-quebec',
    'hydro quebec',
    'hydro',
    'hydro-sherbrooke',
    'hydro sherbrooke',
    'hydro westmount',
    'facture hydro',
    'hydro-joliette',
    'hydro joliette',
    'hydro-magog',
    'hydro magog',
    'hydro-coaticook',
    'coop d electricite',
    'releve de consommation',
    'kwh',
    'kilowattheure',
    'borne de recharge',
    'flo',
    'circuit electrique',
    'chargepoint',
    'hydro-quebec distribution',
    'hydro-quebec production',
    'facture d electricite',
    'tarif d electricite',
    'compteur electrique',
    'compteur intelligent',
    'coop energie',
    'energie renouvelable',
    'panneau solaire',
    'autoproduction electrique',
    'consommation electrique',
    'equilibre hydro-quebec',
    'plan de paiement egal',
    'facturation electrique',
    'tarif domestique',
    'hydro one',
    'hydro ottawa',
    'redevance electrique',
    'gestion de l energie',
    'tarif biernergie',
    'credit hydro-quebec',
    'hydro-magog residentiel',
    'tarif d electricite affaires',
    'gestion energetique maison',
  ],
  chauffage: [
    'chauffage',
    'energir',
    'gaz metro',
    'gaz naturel',
    'mazout',
    'propane',
    'huile a chauffage',
    'bois de chauffage',
    'superieur propane',
    'suncor propane',
    'granules de bois',
    'gaz propane',
    'propane levac',
    'levac',
    'budget propane',
    'filgaz',
    'sonic mazout',
    'mazout sonic',
    'chauffage au bois',
    'poele a bois',
    'fournaise',
    'plancher chauffant',
    'granules energex',
    'energex',
    'super propane',
    'gaz metropolitain',
    'reservoir de propane',
    'remplissage propane',
    'combustible de chauffage',
    'chauffage central',
    'chaudiere',
    'thermopompe chauffage',
    'chauffage biomasse',
    'bois de foyer',
    'corde de bois',
    'granules certifiees',
    'mazout leger',
    'huile domestique',
    'livraison de mazout',
    'reservoir a mazout',
    'reseau de chaleur',
    'chauffage urbain',
    'gaz naturel residentiel',
    'contrat d entretien fournaise',
    'inspection de fournaise',
    'compagnie petroliere',
    'national propane',
    'gaz propane residentiel',
    'distributeur de propane',
    'distributeur mazout regional',
    'service de livraison de propane residentiel',
    'entretien de chaudiere',
  ],
  'entretien-maison': [
    'entretien et reparations',
    'renovation',
    'reno-depot',
    'reno depot',
    'unimat',
    'botanix',
    'jardin hamel',
    'rona',
    'home depot',
    'canac',
    'bmr',
    'home hardware',
    'patrick morin',
    'quincaillerie',
    'plombier',
    'electricien',
    'peinture',
    'deneigement',
    'paysagement',
    'gazon',
    'piscine',
    'ramonage',
    'exterminateur',
    'serrurier',
    'toiture',
    'couvreur',
    'entrepreneur general',
    'climatisation',
    'thermopompe',
    'chauffagiste',
    'inspection en batiment',
    'alarme securite',
    'entretien menager',
    'femme de menage',
    'nettoyage',
    'lowes',
    'lowe s',
    'materiaux',
    'centre de renovation',
    'ace hardware',
    'matco',
    'groupe bmr',
    'agrizone',
    'plomberie',
    'menuisier',
    'renovation cuisine',
    'armoires de cuisine',
    'comptoir de cuisine',
    'nettoyage de conduits',
    'service de menage',
    'menage',
    'lavage de vitres',
    'emondage',
    'arboriculture',
    'pelouse',
    'weed man',
    'nutrite',
    'entretien paysager',
    'deneigement residentiel',
    'fosse septique',
    'vidange de fosse',
    'ramoneur',
    'frais de condo',
    'syndicat de copropriete',
    'gestion de copropriete',
    'arpenteur',
    'excavation',
    'asphaltage',
    'pavage',
    'unipierre',
    'vitrerie',
    'fenetres',
    'portes et fenetres',
    'solaris',
    'vertica',
    'gentek',
    'climatisation service',
    'ramonage de cheminee',
    'puits',
    'traitement d eau',
    'culligan',
    'adoucisseur',
    'outillage',
    'location d outils',
    'location d outillage',
    'simplex',
    'cash location',
    'hertz equipement',
    'battery direct',
    'quincaillerie richelieu',
    'reno jonction',
    'rona plus',
    'ecolodepot',
    'brico',
    'brico depot',
    'les materiaux paysdo',
    'centre du batiment',
    'materiaux paquin',
    'lambert somec',
    'brossard renovation',
    'gedimat',
    'entrepot du plancher',
    'atelier du plancher',
    'ceramique international',
    'ceragres',
    'les ceramiques',
    'cuisine soline',
    'cuisines beauregard',
    'les cuisines',
    'armoires cuisines action',
    'granite depot',
    'comptoirs granite',
    'benoit fenetres',
    'fenetres mq',
    'thermoplast',
    'novatech fenetres',
    'toitures montreal',
    'toiture couture',
    'couvre toit',
    'gouttieres montreal',
    'excavation richard',
    'excavation quebec',
    'terrassement',
    'amenagement paysager',
    'pave uni',
    'permacon',
    'techo-bloc',
    'pisciniste',
    'installation de piscine',
    'trecan',
    'piscines trevi',
    'sunkiss piscines',
    'spa aquilus',
    'baignoire a remous',
    'demenagement',
    'demenageur',
    'transport demenagement',
    'entreposage',
    'location d entrepot',
    'garde-meuble',
    'nettoyeur de tapis',
    'nettoyage de tapis',
    'lavage exterieur maison',
    'nettoyage haute pression',
    'lavage de facade',
    'peinture exterieure',
    'peintre en batiment',
    'debosselage',
    'reparation de fissures',
    'impermeabilisation',
    'impermeabilisation solage',
    'drain francais',
    'fondation reparation',
    'inspecteur en batiment',
    'certification energetique',
    'audit energetique',
    'isolation de grenier',
    'isolation uree formaldehyde',
    'isolation soufflee',
    'entrepreneur en renovation',
    'renovation salle de bain',
    'renovation sous-sol',
    'agrandissement maison',
    'construction neuve',
    'permis de construction',
    'architecte',
    'designer d interieur',
    'dessinateur en batiment',
    'canac-marquis',
    'reno-depot cuisine',
    'excellence renovation',
    'construction renovation',
    'systeme de gicleurs',
    'purificateur d air maison',
    'entretien de piscine',
    'installation de spa',
    'service de plomberie urgence',
    'debouchage de drain',
    'inspection pre-achat',
    'firme d inspection',
    'couvreur montreal',
    'entrepreneur en toiture',
    'gouttiere express',
    'nettoyage de gouttieres',
    'installation de fenetre',
    'design paysager',
    'paysagiste',
    'installation de cloture',
    'terrasse bois',
    'construction de terrasse',
    'service de gicleur incendie',
    'reparation de foyer',
    'installation de foyer',
    'nettoyeur de cheminee',
    'gestion de projet renovation',
    'architecte residentiel',
    'entrepreneur en excavation',
    'location de conteneur',
    'gestion des dechets de construction',
    'location de benne',
    'unimat quincaillerie',
    'canadian tire quincaillerie',
    'home hardware building centre',
    'reno-depot materiaux',
    'bmr express',
    'patrick morin materiaux',
    'quincaillerie richelieu inc',
    'distributeur de materiaux',
    'entrepreneur en plomberie residentielle',
    'entrepreneur electricien residentiel',
    'service de climatisation urgence',
    'installation de thermopompe murale',
    'installation de fournaise electrique',
    'reparation de chauffe-eau',
    'installation de chauffe-eau',
    'compagnie de deneigement residentiel',
    'entreprise de paysagement',
    'design de jardin',
    'pepiniere',
    'centre jardin',
    'jardin botanique boutique',
    'pepiniere locale',
    'paysagiste certifie',
    'service d elagage',
    'compagnie d elagage',
    'service d excavation residentielle',
    'niveleuse',
    'location de mini pelle',
    'location de nacelle',
    'location de compresseur',
    'service de nettoyage haute pression',
    'lavage a pression toiture',
    'lavage a pression entree',
    'nettoyage de facade',
    'compagnie de peinture residentielle',
    'tapissier',
    'poseur de plancher',
    'installateur de ceramique',
    'artisan menuisier',
    'atelier de menuiserie',
    'fabricant d armoires sur mesure',
    'cuisiniste',
    'brico plus quebec',
    'bmr proprietaire',
    'home hardware building supplies',
    'matco quincaillerie',
    'canac materiaux de construction',
    'reno-depot cuisine et salle de bain',
    'entrepreneur en isolation',
    'service d isolation de grenier',
    'compagnie d isolation uree',
    'service de calorifugeage',
    'installateur de gicleurs residentiels',
    'compagnie de traitement d eau residentiel',
    'installateur de systeme septique',
    'compagnie d excavation et de pavage',
    'asphalte drummond',
    'pavage montreal',
  ],
  'meubles-deco': [
    'meubles et deco',
    'ikea',
    'structube',
    'brault et martineau',
    'brault martineau',
    'meubles leon',
    'leons',
    'mobilia',
    'economax',
    'ameublement',
    'homesense',
    'bouclair',
    'linen chest',
    'jysk',
    'wayfair',
    'decoration',
    'meuble',
    'matelas',
    'dormez-vous',
    'dormez vous',
    'sleep country',
    'tanguay',
    'meubles tanguay',
    'urban barn',
    'maison corbeil',
    'corbeil',
    'eq3',
    'zone maison',
    'stokes',
    'pier 1',
    'cb2',
    'crate and barrel',
    'must societe',
    'amnon',
    'jc perreault',
    'meubles rd',
    'meubles bmtc',
    'bmtc',
    'the brick',
    'ashley',
    'ameublement bilodeau',
    'matelas bonheur',
    'sommex',
    'obasan',
    'casper',
    'endy',
    'ikea suede',
    'articles de maison',
    'maison et deco',
    'encadrement',
    'rideaux et stores',
    'stores maison',
    'eclairage',
    'luminaire boutique',
    'multi luminaire',
    'vitrerie decorative',
    'tapis et moquette',
    'couvre-plancher',
    'couvre plancher',
    'planchers',
    'boutique deco',
    'simons maison',
    'at home',
    'home outfitters',
    'solutions rangement',
    'article de maison',
    'meubles usages',
    'design interieur',
    'boutique linge de maison',
    'literie',
    'meubles boisvert',
    'meubles bissonnette',
    'meubles baril',
    'meubles gilbert',
    'ameublement laurier',
    'meubles fournier',
    'design distinctif',
    'la galerie du meuble',
    'idesign',
    'la maison simons deco',
    'artefact deco',
    'article de decoration',
    'article de rangement',
    'panier tresse',
    'meubles patio',
    'ensemble de patio',
    'mobilier de jardin',
    'parasol',
    'chaise longue',
    'balancoire de patio',
    'foyer exterieur',
    'bbq',
    'barbecue',
    'grill exterieur',
    'meuble de rangement exterieur',
    'coussin exterieur',
    'tapis exterieur',
    'article de terrasse',
    'boutique de meubles',
    'meuble quebecois',
    'atelier de meubles',
    'surplus de meubles',
    'showroom mobilier',
    'ameublement moderne',
    'mobilier de bureau',
    'centre de liquidation meubles',
    'design distinct',
    'meubles sur mesure',
    'atelier ebeniste',
    'fabricant de meubles',
    'boutique de rideaux sur mesure',
    'atelier de tapisserie',
    'magasin de tapis oriental',
    'boutique de miroirs',
    'boutique de cadres sur mesure',
    'atelier d encadrement',
    'boutique scandinave deco',
    'boutique boheme deco',
    'magasin de lampes',
    'boutique eclairage design',
    'fabricant de meubles quebecois',
    'atelier bois massif',
    'boutique deco industrielle',
    'magasin de coussins decoratifs',
    'boutique de vaisselle fine',
    'magasin de linge de maison premium',
    'boutique matelas orthopedique',
    'boutique meubles rustiques',
    'boutique meubles scandinaves montreal',
    'atelier meuble artisan quebecois',
    'boutique linge de maison simons',
    'boutique deco maison birks',
  ],

  // telecom
  internet: [
    'internet',
    'videotron',
    'bell',
    'telus',
    'rogers',
    'ebox',
    'oxio',
    'cogeco',
    'distributel',
    'teksavvy',
    'fibe',
    'helix',
    'wifi',
    'fournisseur internet',
    'xittel',
    'vmedia',
    'acanac',
    'starlink',
    'beanfield',
    'colba',
    'electronic box',
    'shaw',
    'eastlink',
    'internet residentiel',
    'forfait internet',
    'modem',
    'routeur',
    'installation internet',
    'fibre optique',
    'fibre',
    'megabit',
    'gigabit',
    'reseau maison',
    'point d acces wifi',
    'wifi mesh',
    'forfait internet residentiel',
    'internet haute vitesse',
    'internet illimite',
    'raccordement internet',
    'installation modem',
    'location de modem',
    'videotron internet',
    'bell internet',
    'internet satellite',
    'xplornet',
    'cablevision',
    'reseau cable',
    'panne internet',
    'service technique internet',
    'internet rural',
    'satellite internet',
    'fournisseur de fibre optique',
    'installation fibre',
    'service technicien internet',
    'fournisseur de telecommunications residentiel',
    'service internet commercial',
    'reparation de reseau internet',
  ],
  // Sans « telephone » : tout recu imprime son numero sous ce mot.
  cellulaire: [
    'cellulaire',
    'fizz',
    'koodo',
    'virgin plus',
    'virgin',
    'freedom mobile',
    'freedom',
    'public mobile',
    'chatr',
    'lucky mobile',
    'bell mobilite',
    'telus mobilite',
    'rogers',
    'videotron mobile',
    'forfait mobile',
    'recharge prepayee',
    'carte sim',
    'sim card',
    'telephone cellulaire',
    'forfait cellulaire',
    'chatr mobile',
    'petro-canada mobilite',
    'mobilite',
    'telephone mobile',
    'recharge cellulaire',
    'data mobile',
    'itinerance',
    'roaming',
    'sim prepayee',
    'telephone intelligent',
    'boutique telus',
    'boutique bell',
    'boutique videotron',
    'wireless',
    'zoomer wireless',
    'petro-canada mobile',
    'good2go mobile',
    'sugar mobile',
    'ptc mobilite',
    'telephone android',
    'iphone forfait',
    'assurance cellulaire',
    'protection appareil mobile',
    'financement d appareil',
    'appareil finance',
    'plan de donnees',
    'forfait de donnees',
    'appel interurbain',
    'frais d itinerance',
    'recharge fizz',
    'recharge koodo',
    'carte esim',
    'forfait illimite',
    'sms illimite',
    'boutique mobilite',
    'reparation cellulaire',
    'source telecom',
    'best buy mobile',
    'walmart mobilite',
    'costco mobilite',
    'forfait famille cellulaire',
    'location d appareil cellulaire',
    'sim internationale',
    'boutique fido',
    'fido',
    'protection d appareil',
    'boutique freedom mobile',
    'boutique koodo',
    'boutique virgin plus',
    'reparation ecran cellulaire',
  ],

  // alimentation
  epicerie: [
    'epicerie',
    'metro',
    'iga',
    'maxi',
    'super c',
    'provigo',
    'loblaws',
    'costco',
    'walmart',
    'mayrand',
    'tigre geant',
    'adonis',
    'avril',
    'rachelle-bery',
    'rachelle bery',
    'marche richelieu',
    'bonichoix',
    'tradition',
    'intermarche',
    'supermarche',
    'marche',
    'fruiterie',
    'boucherie',
    'boulangerie',
    'poissonnerie',
    'depanneur',
    'tabagie',
    'aliments',
    'nourriture',
    'iga extra',
    'marche public',
    'epicerie fine',
    'iga express',
    'metro plus',
    'maxi et cie',
    'provigo le marche',
    'loblaw',
    'real canadian superstore',
    'superstore',
    'wholesale club',
    'club entrepot',
    'sobeys',
    'safeway',
    'freshco',
    'fresh co',
    'no frills',
    'food basics',
    'farm boy',
    'longos',
    'whole foods',
    'marche ami',
    'axep',
    'boni-soir',
    'boni soir',
    'voisin',
    'marche omni',
    'marche express',
    'marche adonis',
    'kim phat',
    'marche c&t',
    't&t',
    'marche oriental',
    'hawai supermarche',
    'sami fruits',
    'fruiterie 440',
    'marche 440',
    'supermarche pa',
    'marche pa',
    'marche atwater',
    'marche jean-talon',
    'marche jean talon',
    'segal',
    'bulk barn',
    'tau',
    'avril supermarche',
    'panier sante',
    'aliments naturels',
    'marche de l ouest',
    'premiere moisson',
    'au pain dore',
    'boulangerie artisanale',
    'patisserie',
    'chocolaterie',
    'fromagerie',
    'cremerie',
    'miellerie',
    'erabliere',
    'cabane a sucre',
    'poissonnerie du marche',
    'boucherie de campagne',
    'abattoir',
    'vergers',
    'autocueillette',
    'kiosque maraicher',
    'marche fermier',
    'ferme',
    'fermes',
    'fraisiere',
    'framboisiere',
    'bleuetiere',
    'chevrerie',
    'cooperative alimentaire',
    'coop alimentaire',
    'epicerie en ligne',
    'instacart',
    'marche goodfood',
    'voila',
    'grocery',
    'supermarket',
    'produce',
    'iga marche',
    'metro richelieu',
    'super marche',
    'marche andre',
    'marche st-jacques',
    'marche saint-jacques',
    'marche des saveurs',
    'marche solidaire',
    'depanneur couche-tard',
    'depanneur alimentation',
    'boucherie du coin',
    'boucherie savoie',
    'boucherie chez vic',
    'poissonnerie shamrock',
    'fruiterie chez louis',
    'fruiterie ontario',
    'fromagerie hamel',
    'fromagerie atwater',
    'boulangerie automatic',
    'boulangerie guillaume',
    'boulangerie premiere moisson',
    'chez tousignant',
    'ferme des voix',
    'kim fung',
    'super marche pa',
    'super marche pa & fils',
    'quatre freres',
    'marche 4 freres',
    'marche akhavan',
    'akhavan',
    'depot patriote',
    'marche des epices',
    'la vieille europe',
    'olives et epices',
    'gourmet laurier',
    'boucherie la ferme',
    'boucherie vaillancourt',
    'poissonnerie la mer',
    'ippolito',
    'ippolito fruits',
    'canasia',
    'd aragona',
    'la moisson',
    'epicerie coreenne',
    'epicerie asiatique',
    'epicerie moyen-orient',
    'epicerie latino',
    'epicerie halal',
    'boucherie halal',
    'marche halal',
    'epicerie kasher',
    'aliments kasher',
    'iga famille',
    'metro famille',
    'marche traiteur',
    'panier bio',
    'lufa',
    'les fermes lufa',
    'marche solidaire frontenac',
    'epicerie zero dechet',
    'vrac et bocaux',
    'walmart supercentre',
    'costco entrepot',
    'epicerie du monde',
    'boucherie casher',
    'poissonnerie du quartier',
    'fromagerie du marche',
    'boulangerie artisanale du coin',
    'super marche bonisoir',
    'ferme maraichere',
    'marche public de quebec',
    'marche public de sherbrooke',
    'marche de la gare',
    'depanneur 7 jours',
    'metro super',
    'provigo maxi',
    'thrifty foods',
    'valu-mart',
    'grocery outlet',
    'save on foods',
    'fortinos',
    'zehrs',
    'independent grocer',
    'your independent grocer',
    'the loop grocery',
    'epicerie latine',
    'epicerie mediterraneenne',
    'epicerie moyen orient',
    'supermarche antillais',
    'depanneur du coin',
    'cooperative bio',
    'iga extra montreal',
    'metro plus quebec',
    'maxi laval',
    'provigo le marche gatineau',
    'super c longueuil',
    'walmart supercentre laval',
    'costco wholesale',
    'costco gatineau',
    'costco levis',
    'sobeys quebec',
    'iga famille jean-talon',
    'metro richelieu ville',
    'adonis ahuntsic',
    'adonis anjou',
    'mourelatos',
    'boucherie st-vincent',
    'boucherie the boucherie',
    'patisserie kouign amann',
    'patisserie rolling pin',
    'chocolats favoris',
    'boutique gourmande',
    'epicerie fine du marche',
    'epicerie bio du coin',
    'marche bonsecours',
    'marche jean talon boutique',
    'marche atwater boutique',
    'aliments merlin',
    'aliments massawippi',
    'depanneur variete',
    'depanneur multi services',
    'depanneur la binerie',
    'vrac en ligne',
    'vrac et cie',
    'bulk barn vrac',
    'fruiterie hazel',
    'fruiterie milano',
    'fruiterie sami',
    'marche du village',
    'marche champlain',
    'epicerie de nuit',
    'epicerie 24 heures',
    'epicerie halal express',
    'epicerie internationale',
    'boucherie portugaise',
    'boucherie polonaise',
    'charcuterie europeenne',
    'fromagerie fine',
    'laiterie',
    'laiterie chalifoux',
    'yannick fromagerie',
    'fromagerie du presbytere',
    'boulangerie premiere moisson cafe',
    'eco marche',
    'eco epicerie',
    'zero dechet epicerie',
    'vrac emballage reutilisable',
    'loblaws quebec',
    'provigo express',
    'iga express depanneur',
    'metro express',
    'iga rive-sud',
    'iga rosemont',
    'metro victoria',
    'metro hochelaga',
    'maxi rimouski',
    'maxi trois-rivieres',
    'provigo chicoutimi',
    'super c gatineau',
    'costco boucherville',
    'costco anjou',
    'sobeys gaspesie',
    'walmart supercentre quebec',
    'marche adonis complexe desjardins',
    'marche kim fung',
    'marche hawaii',
    'epicerie asiatique loblaws',
    'epicerie latino americaine',
    'epicerie africaine',
    'epicerie indienne',
    'epicerie moyen-orient akhavan',
    'epicerie coreenne h mart',
    'h mart',
    'marche wai kee',
    'wai kee',
    'marche man wah',
    'marche pt loblaws',
    'boucherie viandes de choix',
    'boucherie chez louis',
    'poissonnerie nouveau falero',
    'poissonnerie la mer boutique',
    'fromagerie qui roule',
    'fromagerie copette',
    'boulangerie de froment',
    'patisserie chez suzanne',
    'chocolaterie genevieve grandbois',
    'chocolats andree',
    'cabane a sucre au pied de cochon',
    'erabliere meunier',
    'miellerie lune de miel',
    'reseau des fermiers de famille',
    'marche solidaire frontenac boutique',
    'cooperative la maison verte',
    'depanneur nature',
  ],
  restaurant: [
    'restaurant',
    'mcdo',
    'mcdonald',
    'mcdonalds',
    'tim hortons',
    'tims',
    'st-hubert',
    'st hubert',
    'la cage',
    'cage aux sports',
    'normandin',
    'chez ashton',
    'ashton',
    'subway',
    'a&w',
    'harveys',
    'mary browns',
    'souvlaki',
    'ben & florentine',
    'freshii',
    'tutti frutti',
    'booster juice',
    'jugo juice',
    'wendys',
    'burger king',
    'pfk',
    'kfc',
    'valentine',
    'benny',
    'la belle province',
    'belle province',
    'boston pizza',
    'pacini',
    'scores',
    'mikes',
    'chez cora',
    'allo mon coco',
    'eggspectation',
    'thai express',
    'sushi shop',
    'sushi',
    'pizzeria',
    'pizza',
    'resto',
    'bistro',
    'brasserie',
    'casse-croute',
    'casse croute',
    'poutine',
    'tacos',
    'poke bowl',
    'shawarma',
    'cantine',
    'traiteur',
    'buffet',
    'delicatessen',
    'smoked meat',
    'creperie',
    'brunch',
    'st-hubert express',
    'rotisserie',
    'baton rouge',
    'houston',
    'bar b barn',
    'east side marios',
    'east side mario',
    'swiss chalet',
    'montanas',
    'the keg',
    'keg',
    'moxies',
    'earls',
    'milestones',
    'jack astor',
    '3 brasseurs',
    'les 3 brasseurs',
    'trois brasseurs',
    'archibald',
    'dairy queen',
    'popeyes',
    'five guys',
    'taco bell',
    'chipotle',
    'copper branch',
    'mandys',
    'lola rosa',
    'basha',
    'amir',
    'boustan',
    'nickels',
    'deli',
    'schwartz',
    'lafleur',
    'patati patata',
    'frite alors',
    'frites alors',
    'tousignant',
    'dic anns',
    'pizza hut',
    'domino',
    'dominos',
    'pizza pizza',
    'pizza salvatore',
    'salvatore',
    'double pizza',
    'no 900',
    'papa johns',
    'little caesars',
    'sushi taxi',
    'sushi sama',
    'odaki',
    'kanda',
    'mikado',
    'izakaya',
    'ramen',
    'banh mi',
    'thaizone',
    'thai zone',
    'vua',
    'wok',
    'teriyaki',
    'ma poule mouillee',
    'portugalia',
    'romados',
    'rotisserie portugaise',
    'marrakech',
    'tandoori',
    'india beau village',
    'cuisine indienne',
    'grec',
    'cuisine italienne',
    'trattoria',
    'osteria',
    'steakhouse',
    'grill',
    'pub',
    'taverne',
    'resto-bar',
    'resto bar',
    'cafeteria',
    'food court',
    'aire de restauration',
    'comptoir lunch',
    'snack bar',
    'casse-croute du village',
    'roulotte a patates',
    'food truck',
    'camion de rue',
    'chez ti-coq',
    'benny&co',
    'benny co',
    'rotisserie coq',
    'coq roti',
    'poulet frit kentucky',
    'restaurant chinois',
    'buffet chinois',
    'resto asiatique',
    'brasserie artisanale',
    'bistro-bar',
    'diner',
    'restaurant familial',
    'restaurant italien',
    'restaurant thailandais',
    'restaurant vietnamien',
    'restaurant mexicain',
    'restaurant libanais',
    'restaurant indien',
    'restaurant japonais',
    'restaurant coreen',
    'restaurant fusion',
    'restaurant vegetarien',
    'restaurant vegan',
    'bar laitier',
    'la diperie',
    'chocolats favoris',
    'creme glacee molle chaine',
    'valentine glace',
    'bilboquet',
    'kem coba',
    'les givres',
    'cafe cherrier',
    'les enfants terribles',
    'brit and chips',
    'nouilles de lan zhou',
    'zibo',
    'exotic garden',
    'la khaima',
    'restaurant vietnam',
    'restaurant szechuan',
    'restaurant cantonais',
    'buffet des continents',
    'buffet bonanza',
    'buffet mandarin',
    'buffet la caravelle',
    'auberge du dragon rouge',
    'la maree',
    'restaurant de fruits de mer',
    'grillades portugaises',
    'chalet bbq',
    'poulet frit maison',
    'resto vegan',
    'copper branch resto',
    'la panthere verte',
    'crudessence',
    'aux vivres',
    'lov',
    'invitation v',
    'restaurant santropol',
    'santropol',
    'chez alexandre',
    'reservoir',
    'brouhaha',
    'burger de ville',
    'burger royal',
    'nickels dejeuner',
    'cora dejeuner',
    'toujours dimanche',
    'aux deux marie',
    'restaurant familial vieux montreal',
    'la banquise',
    'chien chaud comptoir',
    'poutinerie',
    'la belle et la boeuf',
    'brasserie t',
    'restaurant halal',
    'restaurant casher',
    'st viateur bagel',
    'fairmount bagel',
    'la queue de cheval',
    'moishes',
    'gibbys',
    'la binerie',
    'wilensky',
    'poulet frit du sud',
    'restaurant portugais',
    'restaurant fruits de mer',
    'cage brasserie sportive',
    'restaurant familial fiesta',
    'delta resto',
    'resto boheme',
    'houston avenue',
    'restaurant marocain',
    'restaurant peruvien',
    'comptoir a burger',
    'comptoir a poutine',
    'comptoir a tacos',
    'resto vietnamien pho',
    'resto italien trattoria',
    'resto japonais teppanyaki',
    'resto coreen bbq',
    'resto indien tandoori house',
    'resto libanais byblos',
    'resto marocain atlas',
    'resto thai basilic',
    'resto peruvien inca',
    'resto grec milos',
    'resto mexicain frida',
    'resto espagnol barcelona',
    'resto fusion asiatique',
    'resto vegetalien lov',
    'resto crudivore',
    'resto smash burger',
    'burger de luxe',
    'comptoir burger gourmet',
    'poutinerie la banquise',
    'poutinerie chez tousignant',
    'boite a poutine',
    'cabane a poutine',
    'resto familial normandin',
    'resto familial cage',
    'resto de quartier bistro l ami',
    'bistro le local',
    'bistro le vin papillon',
    'bistro moleskine',
    'resto brunch cora',
    'resto brunch eggo',
    'resto pub le saint bock',
    'pub le vieux montreal',
    'taverne magnan',
    'taverne joe beef',
    'resto steak boeuf',
    'resto de la mer poisson frais',
    'restaurant montagnais',
    'restaurant erabliere',
    'cabane a sucre chez dany',
    'resto familial saint hubert',
    'resto rapide subway express',
    'resto rapide harveys express',
    'resto rapide wendys drive',
    'resto rapide a et w',
    'comptoir poulet frit',
    'comptoir shawarma boustan',
    'comptoir falafel',
    'resto vegan lov',
    'resto crudivore rawmesan',
    'resto tapas ferreira',
    'resto brasserie brutus',
    'resto le club chasse et peche',
    'resto toque',
    'resto la finca',
    'resto icehouse',
    'resto la salsa',
    'resto la cabane a sucre du village',
    'resto poutine centrale',
    'resto burger bar b barn',
    'resto brasserie brouhaha',
    'resto vietnamien pho tay ho',
    'resto vietnamien pho bang new york',
    'resto thai talay thai',
    'resto japonais jun i',
    'resto indien gandhi',
    'resto libanais anise',
    'resto grec la belle grecque',
    'resto mexicain mexiqui',
    'resto peruvien la table peruvienne',
    'resto coreen manna',
    'resto de fruits de mer le maree haute',
    'resto steakhouse gibbys',
    'resto steakhouse magnan',
  ],
  // Sans « livraison », qui est une ligne de frais sur n'importe quel recu, ni « skip »,
  // trop court pour valoir preuve.
  'livraison-repas': [
    'livraison de repas',
    'uber eats',
    'ubereats',
    'doordash',
    'door dash',
    'skip the dishes',
    'skipthedishes',
    'fantuan',
    'goodfood',
    'hellofresh',
    'cook it',
    'dashpass',
    'ritual',
    'foodora',
    'chefs plate',
    'marche fraiche',
    'miam',
    'allo resto',
    'delivro',
    'livraison a domicile',
    'commande en ligne repas',
    'chef a la maison',
    'boite repas',
    'pret a manger livre',
    'uber eats canada',
    'doordash canada',
    'skip the dishes canada',
    'application de livraison',
    'commande uber',
    'commande doordash',
    'commande skip',
    'menu en ligne',
    'livraison de sushi',
    'livraison de poutine',
    'livraison de pizza',
    'pizza livree',
    'app repas',
    'app de livraison',
    'commande uber eats',
    'livraison de commande',
    'coursier repas',
    'compte doordash',
    'compte uber eats',
    'livraison instantanee repas',
    'service de repas prepares livres',
    'abonnement de repas hebdomadaire',
    'cuisine fantome',
  ],
  // Sans « saint-henri » : un quartier et une rue avant d'etre une brulerie, et les succursales
  // s'impriment au nom de leur quartier (« IGA SAINT-HENRI »). « cafe » suffit a la brulerie.
  cafe: [
    'cafe',
    'starbucks',
    'second cup',
    'presse cafe',
    'cafe depot',
    'van houtte',
    'brulerie',
    'mccafe',
    'tim hortons',
    'nespresso',
    'keurig',
    'torrefaction',
    'java u',
    'pilon',
    'dunkin',
    'cafe william',
    'faro',
    'pikolo',
    'crew collective',
    'myriade',
    'olimpico',
    'cafe olimpico',
    'tommy',
    'dispatch',
    'brulerie st-denis',
    'cafe union',
    'barista',
    'cafe de la rue',
    'torrefacteur',
    'coffee',
    'coffee shop',
    'espresso bar',
    'tim horton',
    'starbucks reserve',
    'mccafe drive',
    'cafe bistro',
    'salon de the',
    'maison de the',
    'davids tea',
    'teavana',
    'bubble tea',
    'the bulles',
    'chatime',
    'cha time',
    'cafe des artistes',
    'cafe italia',
    'cafe replika',
    'cafe saint henri',
    'cafe pista',
    'pikolo espresso bar',
    'anticafe',
    'cafe larue et fils',
    'la brulerie mont-royal',
    'brulerie mont royal',
    'soul cafe',
    'cafe neve',
    'sensei cafe',
    'cafe rico',
    'cafe cognac',
    'cafe le falco',
    'nomade cafe',
    'presse cafe express',
    'starbucks reserve roastery',
    'tim hortons express',
    'tim hortons drive',
    'cafe depot express',
    'cafe des amis',
    'cafe de quartier',
    'cafe artisanal',
    'torrefacteur artisanal',
    'cafe italien',
    'cafe europeen',
    'cafe expresso bar',
    'cafe des arts',
    'salon de the anglais',
    'brulerie du quartier',
    'cafe indie',
    'cafe etudiant',
    'comptoir a cafe',
    'cafe deuxieme tasse',
    'cafe artisan torrefacteur montreal',
    'boutique de the specialise',
  ],
  alcool: [
    'alcool',
    'saq',
    'lcbo',
    'biere',
    'vin',
    'spiritueux',
    'microbrasserie',
    'vignoble',
    'cidrerie',
    'distillerie',
    'boisson alcoolisee',
    'bar a vin',
    'succursale saq',
    'saq express',
    'saq depot',
    'saq selection',
    'saq signature',
    'societe des alcools',
    'societe des alcools du quebec',
    'depanneur biere',
    'broue pub',
    'pub brasseur',
    'la barberie',
    'dieu du ciel',
    'trou du diable',
    'pit caribou',
    'farnham ale',
    'noctem',
    'vices et versa',
    'brasseur de montreal',
    'brasserie artisanale du quebec',
    'boutique de vin',
    'importation privee',
    'agence de vin',
    'caviste',
    'spiritueux artisanaux',
    'hydromel',
    'meaderie',
    'liquor',
    'liquor store',
    'beer store',
    'wine',
    'saq classique',
    'saq inc',
    'succursale de la saq',
    'depanneur boissons',
    'microbrasserie le castor',
    'microbrasserie brasseurs du monde',
    'microbrasserie a l abri de la tempete',
    'brasserie harricana',
    'brasserie oshlag',
    'brasserie le bilboquet',
    'les brasseurs rj',
    'la voie maltee',
    'brasseurs et frereres',
    'brasseurs et freres',
    'menaud',
    'siboire',
    'archibald microbrasserie',
    'le castor',
    'benelux',
    'isle de garde',
    'vice versa',
    'auval',
    'vignoble sainte-petronille',
    'vignoble carone',
    'vignoble de l orpailleur',
    'orpailleur',
    'vignoble les pervenches',
    'cidrerie du minot',
    'cidrerie michel jodoin',
    'cidrerie verger',
    'domaine pinnacle',
    'monna et filles',
    'depanneur vin et fromage',
    'boutique spiritueux',
    'distillerie fils du roy',
    'distillerie cirka',
    'distillerie mariana',
    'sous bois distillerie',
    'oshlag',
    'depanneur alcool',
    'importation de vin',
    'agence de spiritueux',
    'bar a biere',
    'brouepub',
    'brasserie de garage',
    'boutique de biere',
    'club de biere',
    'degustation de vin',
    'vignoble local',
    'vignoble artisanal',
    'distillerie artisanale quebecoise',
    'cidrerie artisanale',
    'biere artisanale locale',
    'microbrasserie artisanale locale',
    'brasserie familiale',
    'cidrerie du verger',
    'vignoble en vallee',
    'distillerie de gin locale',
    'boutique specialisee whisky',
    'cave a vin',
    'importateur prive de vin',
    'club d achat de vin',
    'societe des alcools succursale',
    'depanneur avec permis alcool',
    'microbrasserie le trou du diable',
  ],

  // transport
  vehicule: [
    'paiement du vehicule',
    'pret auto',
    'financement auto',
    'mensualite auto',
    'location long terme',
    'lease',
    'concessionnaire',
    'saaq',
    'immatriculation',
    'permis de conduire',
    'credit auto',
    'leasing',
    'hgregoire',
    'h gregoire',
    'lallier',
    'spinelli',
    'park avenue',
    'john scotti',
    'automobiles',
    'vente d automobiles',
    'auto neuve',
    'auto usagee',
    'concession automobile',
    'location de vehicule long terme',
    'credit-bail',
    'credit bail',
    'solde de financement',
    'pret automobile',
    'transfert de propriete',
    'droit d immatriculation',
    'plaque d immatriculation',
    'renouvellement de permis',
    'moto',
    'vtt',
    'motoneige',
    'roulotte',
    'bateau',
    'toyota financement',
    'honda financement',
    'ford credit',
    'gm financement',
    'nissan financement',
    'hyundai financement',
    'kia financement',
    'volkswagen financement',
    'mazda financement',
    'subaru financement',
    'chrysler financement',
    'stellantis financement',
    'td auto finance',
    'rbc financement auto',
    'scotia financement auto',
    'desjardins financement auto',
    'credit auto national',
    'services financiers automobiles',
    'location a long terme',
    'plan de versements vehicule',
    'auto capital canada',
    'clutch',
    'canada drives',
    'autohebdo vente',
    'vehicule electrique achat',
    'incitatif vehicule electrique',
    'concession toyota',
    'concession honda',
    'concession ford',
    'concession hyundai',
    'concession kia',
    'concession mazda',
    'concession nissan',
    'concession subaru',
    'concession volkswagen',
    'concession chevrolet',
    'auto capital',
    'groupe park avenue',
    'ford lincoln',
    'chrysler canada',
    'automobile usagee',
    'centre de location automobile',
    'financement automobile',
    'vente de vehicule',
    'vente de moto',
    'vente de vtt',
    'vente de motoneige',
    'permis moto',
    'permis vtt',
    'achat vehicule electrique',
    'subvention vehicule electrique',
  ],
  // Sans « libre service » : c'est le nom que les caisses libre-service donnent au caissier
  // (« Servi par: Libre Service 22 » chez IGA). « esso marche express » l'emporte sur
  // « marche express » (epicerie) parce qu'il est plus long : c'est une station-service.
  essence: [
    'essence',
    'petro-canada',
    'petro canada',
    'petro-t',
    'petro t',
    'esso',
    'esso marche express',
    'shell',
    'ultramar',
    'couche-tard',
    'couche tard',
    'irving',
    'crevier',
    'harnois',
    'mobil',
    'costco essence',
    'station-service',
    'station service',
    'carburant',
    'diesel',
    'pompe a essence',
    'valero',
    'circle k',
    'olco',
    'sonic',
    'coop essence',
    'mcewen',
    'pioneer',
    'husky',
    'flying j',
    'chevron',
    'gulf',
    'north atlantic',
    'petro pass',
    'esso on the run',
    'on the run',
    'shell select',
    'depanneur essence',
    'libre-service essence',
    'carte carburant',
    'poste d essence',
    'gaz bar',
    'gasoline',
    'gas station',
    'fuel stop',
    'poste petro-canada',
    'esso circle k',
    'ultramar depanneur',
    'shell station',
    'valero station',
    'gazoline',
    'carburant diesel',
    'poste d essence libre service',
    'irving oil',
    'les petroles crevier',
    'harnois energies',
    'essencerie',
    'station essence 24h',
    'poste esso libre service',
    'poste shell libre service',
    'poste petro-canada 24h',
    'depanneur couche-tard essence',
    'circle k essence',
    'irving essence',
    'poste ultramar 24h',
    'station gulf',
    'station husky',
    'station chevron',
    'station mobil',
    'poste d essence rural',
    'cooperative agricole essence',
    'sonic depanneur essence',
    'poste olco',
    'poste pioneer essence',
  ],
  'assurance-auto': [
    'assurance auto',
    'assurance vehicule',
    'assurance automobile',
    'intact',
    'beneva',
    'belairdirect',
    'belair direct',
    'la capitale',
    'promutuel',
    'desjardins assurances',
    'industrielle alliance',
    'allstate',
    'sonnet',
    'aviva',
    'wawanesa',
    'economical',
    'td assurance',
    'meloche monnex',
    'assurance moto',
    'assurance vr',
    'prime d assurance auto',
    'ssq auto',
    'la personnelle auto',
    'unique assurances',
    'pafco',
    'coseco',
    'optimum assurance',
    'lussier dale parizeau',
    'courtier en assurance',
    'contribution d assurance saaq',
    'avenant',
    'assurance vehicule recreatif',
    'garantie prolongee vehicule',
    'protection pneus et jantes',
    'assurance collision',
    'assurance responsabilite civile auto',
    'courtier auto assurance',
    'assurance moto quebec',
    'assurance vus',
    'assurance vehicule commercial',
    'chubb assurance auto',
    'assurance tous risques',
    'franchise assurance auto',
    'prime mensuelle assurance auto',
    'renouvellement assurance auto',
    'baisse de prime',
  ],
  'entretien-vehicule': [
    'entretien du vehicule',
    'garage',
    'mecanicien',
    'changement d huile',
    'vidange d huile',
    'pneus',
    'pneu',
    'canadian tire',
    'mr lube',
    'monsieur muffler',
    'midas',
    'napa',
    'lave-auto',
    'lave auto',
    'carrosserie',
    'silencieux',
    'freins',
    'antirouille',
    'krown',
    'docteur du pare-brise',
    'pare-brise',
    'pare brise',
    'batterie auto',
    'remorquage',
    'transmission',
    'speedy',
    'point s',
    'uni-select',
    'uni select',
    'partsource',
    'part source',
    'carquest',
    'bumper to bumper',
    'pieces d auto',
    'centre du pneu',
    'centre de l auto',
    'atelier mecanique',
    'fix auto',
    'carstar',
    'boyd',
    'novus',
    'speedy glass',
    'vitrerie d auto',
    'esthetique automobile',
    'traitement antirouille',
    'garage bosch',
    'service auto',
    'atelier de mecanique',
    'inspection mecanique',
    'toyota service',
    'honda service',
    'ford service',
    'pieces et accessoires',
    'auto value',
    'tirecraft',
    'tire craft',
    'pneus ratte',
    'maxi pneus',
    'sos remorquage',
    'cai remorquage',
    'cireur auto',
    'garage mecanique general',
    'atelier de reparation auto',
    'centre de service pneus',
    'canadian tire auto',
    'centre du camion',
    'boutique de pieces auto',
    'reparation de pare-brise',
    'installation de pneus hiver',
    'entreposage saisonnier de pneus',
    'atelier de carrosserie',
    'expertise en carrosserie',
    'estimation de dommages',
    'garage independant',
    'mecanique generale',
    'service rapide auto',
  ],
  stationnement: [
    'stationnement',
    'parking',
    'parcometre',
    'horodateur',
    'indigo',
    'impark',
    'stationnement de montreal',
    'stationnement souterrain',
    'stationnement de quebec',
    'stationnement ville',
    'precise parklink',
    'parkwhiz',
    'stationnement aeroport',
    'vignette de stationnement',
    'borne de paiement',
    'espace stationnement',
    'parc-o-bus',
    'parc o bus',
    'garage municipal',
    'stationnement mensuel',
    'parking lot',
    'stationnement centre-ville',
    'stationnement incitatif',
    'permis de stationnement',
    'zone de stationnement',
    'stationnement gatineau',
    'reseau de stationnement',
    'lot de stationnement prive',
    'stationnement hopital',
    'stationnement universite',
    'stationnement gare',
    'stationnement hopital sainte-justine',
    'tarif de stationnement quotidien',
  ],
  'transport-commun': [
    'transport en commun',
    'stm',
    'rtc',
    'stl',
    'rtl',
    'exo',
    'opus',
    'autobus',
    'metro de montreal',
    'train',
    'via rail',
    'orleans express',
    'bixi',
    'transport adapte',
    'presto',
    'sto',
    'sts',
    'stsaguenay',
    'societe de transport',
    'amt',
    'reseau express metropolitain',
    'megabus',
    'intercar',
    'limocar',
    'autocar',
    'keolis',
    'taxibus',
    'navette aeroport',
    'titre mensuel',
    'carte opus',
    'recharge opus',
    'reseau de transport de longueuil',
    'societe de transport de laval',
    'societe de transport de levis',
    'transport collectif',
    'carte mensuelle stm',
    'zone tarifaire exo',
    'train de banlieue',
    'ligne exo',
    'reseau structurant',
    'transport reseau metropolitain',
    'reseau structurant de transport en commun',
    'carte mensuelle exo',
    'societe de transport de sherbrooke',
  ],
  taxi: [
    'taxi et covoiturage',
    'uber',
    'eva',
    'taxi coop',
    'taxi diamond',
    'covoiturage',
    'communauto',
    'teo taxi',
    'lyft',
    'coop taxi',
    'taxi bonjour',
    'taxi para-adapte',
    'taxi hochelaga',
    'taxi 5000',
    'taxi de quebec',
    'bond taxi',
    'ride share',
    'course uber',
    'eva coop',
    'course de taxi',
    'reservation de taxi',
    'taxi aeroport',
    'application de covoiturage',
    'via covoiturage',
    'kangaride',
    'transport reference client',
    'service de limousine',
    'transport medical adapte',
    'chauffeur prive',
  ],

  // sante
  medicaments: [
    'medicaments',
    'jean coutu',
    'pharmaprix',
    'uniprix',
    'familiprix',
    'brunet',
    'proxim',
    'acces pharma',
    'pharmacie',
    'prescription',
    'ordonnance',
    'vaccin',
    'shoppers',
    'shoppers drug mart',
    'pharmasave',
    'rexall',
    'london drugs',
    'pharmachoice',
    'pharmacie du village',
    'costco pharmacie',
    'walmart pharmacie',
    'pharmacie familiale',
    'medicament d ordonnance',
    'renouvellement d ordonnance',
    'pilulier',
    'pharmacien',
    'drug mart',
    'pharmacy',
    'pharmacie proxim reseau',
    'pharmacie jean coutu reseau',
    'pharmacie brunet reseau',
    'centre de sante pharmacie',
    'clinique pharmacie',
    'pharmacie 24h',
    'pharmacie de garde',
    'pharmacie communautaire',
    'pharmacie de nuit',
    'pharmacie du centre-ville',
    'pharmacie de quartier',
    'clinique pharmaceutique',
    'pharmacie communautaire independante',
    'clinique pharmacie proxim reseau familial',
  ],
  // Sans « urgence », qui s'imprime sur des recus n'ayant rien de medical, ni « sans
  // rendez-vous », que la coiffure imprime autant que la clinique.
  'soins-medicaux': [
    'soins medicaux',
    'clinique',
    'medecin',
    'physiotherapie',
    'physio',
    'chiropraticien',
    'chiro',
    'osteopathe',
    'osteo',
    'massotherapie',
    'massage',
    'optometriste',
    'lunettes',
    'lunetterie',
    'new look',
    'iris',
    'greiche scaff',
    'psychologue',
    'therapie',
    'acupuncture',
    'podiatre',
    'laboratoire',
    'prise de sang',
    'biron',
    'ramq',
    'ergotherapie',
    'nutritionniste',
    'dietetiste',
    'audiologiste',
    'orthophoniste',
    'sage-femme',
    'sage femme',
    'clinique medicale',
    'hopital',
    'chsld',
    'clinique privee',
    'lasik md',
    'lasik',
    'ophtalmologie',
    'audioprothesiste',
    'lobe',
    'clinique auditive',
    'dermatologue',
    'telemedecine',
    'maple',
    'imagerie medicale',
    'radiologie',
    'echographie',
    'irm',
    'clsc',
    'physio extra',
    'action sport physio',
    'kinesiologue',
    'naturopathe',
    'sexologue',
    'travailleur social',
    'psychotherapie',
    'psychiatre',
    'clinique de fertilite',
    'vaccination voyage',
    'clinique du voyageur',
    'orthesiste',
    'orthese',
    'prothese',
    'medical',
    'clinic',
    'clinique sans rendez vous',
    'groupe medical',
    'super clinique',
    'clinique reseau sante',
    'clinique medicale familiale',
    'clinique de readaptation',
    'centre de readaptation',
    'physiotherapie sport',
    'centre de physiotherapie',
    'clinique podiatrique',
    'clinique de kinesiologie',
    'centre de massotherapie',
    'clinique multidisciplinaire',
    'clinique de sante mentale',
    'clinique de sante integree',
    'centre medical prive',
    'clinique de premiere ligne',
    'clinique de sante voyage',
    'reseau sante prive',
    'clinique physiotherapie sport medecine',
  ],
  dentiste: [
    'dentiste',
    'dentaire',
    'clinique dentaire',
    'orthodontiste',
    'hygieniste',
    'nettoyage dentaire',
    'broches',
    'invisalign',
    'couronne dentaire',
    'extraction dentaire',
    'plombage',
    'centre dentaire',
    'denturologiste',
    'denturologie',
    'endodontiste',
    'parodontiste',
    'implant dentaire',
    'clinique d orthodontie',
    'dentalcorp',
    'soins dentaires',
    'prothese dentaire',
    'blanchiment dentaire',
    'dental',
    'dentiste familial',
    'centre dentaire familial',
    'clinique d implantologie',
    'denturologiste clinique',
    'clinique d orthodontie invisalign',
    'clinique dentaire pediatrique',
    'urgence dentaire 24h',
    'reseau dentaire',
    'clinique dentaire du quartier',
    'clinique dentaire reseau dentalcorp',
    'clinique d hygiene dentaire',
  ],
  // Sans « saint-sauveur » : une ville avant d'etre une station de ski.
  sport: [
    'sport et gym',
    'gym',
    'econofitness',
    'econo fitness',
    'nautilus',
    'energie cardio',
    'world gym',
    'goodlife',
    'fitness',
    'entrainement',
    'yoga',
    'crossfit',
    'natation',
    'hockey',
    'soccer',
    'golf',
    'tennis',
    'escalade',
    'centre de ski',
    'ski alpin',
    'abonnement gym',
    'club de golf',
    'centre sportif',
    'velo',
    'patinoire',
    'karate',
    'arts martiaux',
    'ymca',
    'nautilus plus',
    'buzz fitness',
    'orangetheory',
    'f45',
    'anytime fitness',
    'planet fitness',
    'carrefour multisports',
    'studio de yoga',
    'pilates',
    'spinning',
    'boxe',
    'judo',
    'taekwondo',
    'gymnastique',
    'arena',
    'centre aquatique',
    'piscine municipale',
    'club de course',
    'ligue de garage',
    'tournoi',
    'mont tremblant',
    'bromont',
    'sommet',
    'stoneham',
    'le massif',
    'le relais',
    'vallee du parc',
    'owl s head',
    'ski de fond',
    'raquette',
    'camp d entrainement',
    'club sportif',
    'terrain de golf',
    'practice de golf',
    'quilles sport',
    'curling',
    'badminton',
    'squash',
    'escrime',
    'athletisme',
    'triathlon',
    'marathon',
    'inscription course',
    'dossard',
    'centre multisports',
    'club de tennis',
    'club de squash',
    'complexe sportif',
    'boutique de plein air',
    'altitude sports',
    'mountain equipment coop',
    'la cordee',
    'antidote sports',
    'boutique de velo',
    'cycles gervais',
    'centre national',
    'academie de hockey',
    'academie de soccer',
    'club de patinage artistique',
    'boutique de course a pied',
    'boutique de natation',
    'boutique de patins et hockey',
    'boutique de ski et planche',
    'boutique de velo de montagne',
    'atelier de reparation de velo',
    'club de course a pied',
    'academie de golf',
    'centre d entrainement personnel',
    'studio de pilates',
    'studio de crossfit',
    'academie de natation',
    'ecole de golf',
    'boutique de plein air aventure',
    'boutique endurance triathlon',
    'boutique de plein air le baron',
    'boutique de camping national',
    'boutique de peche pecheur du quebec',
  ],

  // personnel
  // Sans « mode », imprime dans « Mode de paiement » sur la plupart des recus — « mode choc »
  // nomme l'enseigne sans ce defaut. Sans « la baie » : l'enseigne a ferme en 2025, et le nom
  // reste celui d'une ville. Sans « boutique » : on en tient de meubles, de cadeaux, de velos.
  vetements: [
    'vetements',
    'simons',
    'winners',
    'h&m',
    'zara',
    'uniqlo',
    'old navy',
    'gap',
    'shein',
    'sports experts',
    'aubainerie',
    'ardene',
    'reitmans',
    'rw&co',
    'dynamite',
    'lululemon',
    'nike',
    'adidas',
    'foot locker',
    'browns',
    'aldo',
    'chaussures',
    'souliers',
    'bottes',
    'manteau',
    'linge',
    'friperie',
    'village des valeurs',
    'moores',
    'tristan',
    'sail',
    'atmosphere',
    'decathlon',
    'urban outfitters',
    'american eagle',
    'marks',
    'mark s',
    'l equipeur',
    'sportium',
    'sports rousseau',
    'ssense',
    'frank and oak',
    'frank oak',
    'bikini village',
    'la vie en rose',
    'la senza',
    'roots',
    'canada goose',
    'columbia',
    'north face',
    'under armour',
    'puma',
    'new balance',
    'vans',
    'converse',
    'skechers',
    'globo',
    'chaussures pop',
    'little burgundy',
    'call it spring',
    'bentley',
    'pandora',
    'swarovski',
    'michael kors',
    'marshalls',
    'psyche',
    'boutique de vetements',
    'pret a porter',
    'mode choc',
    'vetements pour enfants',
    'carters',
    'childrens place',
    'gymboree',
    'souris mini',
    'deux par deux',
    'orchestra',
    'boutique bebe',
    'bonneterie',
    'cordonnerie',
    'retouches',
    'couturiere',
    'nettoyeur',
    'buanderie',
    'clothing',
    'apparel',
    'shoes',
    'boutique vetements enfants',
    'boutique vetements homme',
    'boutique vetements femme',
    'grande taille boutique',
    'addition elle',
    'penningtons',
    'boutique laura',
    'melanie lyne',
    'boutique jacob',
    'le chateau',
    'suzy shier',
    'boutique cleo',
    'boutique bootlegger',
    'boutique urban planet',
    'garage clothing',
    'costco vetements',
    'boutique de sport vetements',
    'boutique de sport gymnastique vetements',
    'boutique de vetements outdoor',
    'boutique running vetements',
    'boutique de mode locale',
    'boutique de mode vintage',
    'friperie eva b',
    'friperie renaissance',
    'friperie fripe prive',
    'boutique de mode ethique',
    'atelier de couture sur mesure',
    'boutique tissu',
    'boutique de sous-vetements',
    'boutique lingerie fine',
    'boutique de maillots de bain',
    'boutique manteaux d hiver',
    'boutique de chaussures de sport',
    'boutique de bottes de travail',
    'boutique de vetements de motoneige',
    'boutique de vetements de plein air',
    'kanuk',
    'quartier general',
    'mec plein air vetements',
    'chlorophylle vetements',
    'boutique bebe vetements',
    'carters oshkosh',
    'boutique enfant chic',
    'boutique ado mode',
    'boutique grande taille penningtons',
    'boutique de robes de soiree',
    'boutique de complets homme',
    'tailleur sur mesure',
    'cordonnerie express',
    'boutique de chapeaux',
    'boutique de gants d hiver',
    'boutique accessoires de mode',
    'boutique de vetements outdoor sail',
    'boutique de vetements outdoor atmosphere plein air',
    'boutique de sport experts vetements',
    'boutique jean coutu vetements bebe',
    'boutique canadian tire vetements travail',
    'boutique de vetements de travail mark s',
    'boutique de vetements de securite',
    'boutique de vetements chasse et peche',
    'boutique de vetements de motoneige ski-doo',
    'boutique de vetements de plein air kanuk montreal',
  ],
  'soins-personnels': [
    'coiffure et soins',
    'coiffeur',
    'salon de coiffure',
    'barbier',
    'barber shop',
    'esthetique',
    'estheticienne',
    'manucure',
    'pedicure',
    'ongles',
    'epilation',
    'spa detente',
    'strom',
    'bota bota',
    'scandinave',
    'sephora',
    'produits de beaute',
    'cosmetiques',
    'maquillage',
    'lush',
    'rasage',
    'yves rocher',
    'tatouage',
    'piercing',
    'parfumerie',
    'the body shop',
    'body shop',
    'bath and body works',
    'ulta',
    'marcelle',
    'nail bar',
    'salon d ongles',
    'spa nordique',
    'balnea',
    'ofuro',
    'sky spa',
    'institut de beaute',
    'centre d epilation',
    'epilation au laser',
    'electrolyse',
    'magicuts',
    'great clips',
    'first choice',
    'tchip',
    'coiffure',
    'salon de beaute',
    'microblading',
    'extensions de cils',
    'pose d ongles',
    'bronzage',
    'salon de bronzage',
    'soins du visage',
    'produits capillaires',
    'beaute',
    'hair salon',
    'nails',
    'spa',
    'salon de coiffure unisexe',
    'salon prive coiffure',
    'institut esthetique',
    'spa urbain',
    'clinique de beaute laser',
    'medi spa',
    'clinique dermatologique esthetique',
    'boutique de parfums',
    'sephora boutique',
    'shoppers beaute',
    'jean coutu beaute',
    'salon esthetique complet',
    'boutique de soins naturels',
    'herboristerie',
    'boutique de produits bio beaute',
    'institut de bronzage',
    'salon de tatouage artistique',
    'studio de piercing',
    'boutique de perruques',
    'salon capillaire afro',
    'salon coiffure homme barbier',
    'boutique de cosmetiques coreens',
    'boutique de soins de la peau',
    'clinique de microblading',
    'clinique d epilation permanente',
    'boutique de produits capillaires naturels',
    'salon de coiffure premiere classe',
    'salon de coiffure tendance',
    'institut beaute laurentienne',
    'spa nordique le finlandais',
    'spa nordique sibou',
  ],

  // loisirs
  streaming: [
    'abonnements et streaming',
    'netflix',
    'spotify',
    'disney plus',
    'disney',
    'crave',
    'prime video',
    'amazon prime',
    'apple tv',
    'apple music',
    'icloud',
    'youtube premium',
    'hbo',
    'paramount',
    'illico',
    'club illico',
    'tou tv',
    'deezer',
    'twitch',
    'patreon',
    'google one',
    'microsoft 365',
    'office 365',
    'dropbox',
    'chatgpt',
    'openai',
    'canva',
    'tva plus',
    'noovo',
    'adobe',
    'creative cloud',
    'peacock',
    'discovery plus',
    'britbox',
    'crunchyroll',
    'mubi',
    'shudder',
    'plex',
    'tidal',
    'soundcloud',
    'vimeo',
    'substack',
    'notion',
    'slack',
    'zoom',
    'github',
    'onedrive',
    'google drive',
    'nordvpn',
    'nord vpn',
    'express vpn',
    '1password',
    'lastpass',
    'anthropic',
    'claude ai',
    'midjourney',
    'sirius xm',
    'siriusxm',
    'audible abonnement',
    'apple one',
    'amazon music',
    'hulu',
    'starz',
    'super ecran',
    'abonnement mensuel numerique',
    'abonnement annuel',
    'subscription',
    'renouvellement automatique',
    'abonnement crave plus',
    'abonnement disney premium',
    'forfait combo streaming',
    'bundle streaming',
    'illico plus',
    'service de diffusion en continu',
    'abonnement musique en continu',
    'service de vod',
    'location de film en ligne',
  ],
  'jeux-video': [
    'jeux video',
    'steam',
    'playstation',
    'ps plus',
    'xbox',
    'game pass',
    'nintendo',
    'nintendo eshop',
    'eb games',
    'gamestop',
    'epic games',
    'blizzard',
    'ea play',
    'riot',
    'app store',
    'google play',
    'playstation network',
    'ubisoft',
    'oculus',
    'meta quest',
    'humble bundle',
    'gog',
    'itch io',
    'battle net',
    'battlenet',
    'origin',
    'rockstar',
    'square enix',
    'bandai',
    'capcom',
    'microsoft store',
    'nintendo store',
    'microplay',
    'level up',
    'retro gaming',
    'jeux usages',
    'console de jeu',
    'manette de jeu',
    'carte prepayee jeux',
    'psn',
    'eshop',
    'steam wallet',
    'gaming',
    'esport',
    'boutique jeux video usages',
    'jeux video usages',
    'micro store jeux',
    'boutique de jeux retro',
    'boutique de jeux retro montreal',
    'location de jeux video',
  ],
  // Sans « soiree » : « Merci et bonne soiree! » s'imprime sur des recus de toute sorte.
  sorties: [
    'sorties et spectacles',
    'cinema',
    'cineplex',
    'guzzo',
    'spectacle',
    'concert',
    'billet',
    'ticketmaster',
    'evenko',
    'theatre',
    'musee',
    'la ronde',
    'osheaga',
    'festival',
    'quilles',
    'billard',
    'escape room',
    'arcade',
    'karaoke',
    'place des arts',
    'juste pour rire',
    'aquarium',
    'zoo',
    'jardin botanique',
    'bowling',
    'patinage',
    'cineplex odeon',
    'cinema banque scotia',
    'cinema beaubien',
    'cinema du parc',
    'starcite',
    'imax',
    'cineplex vip',
    'theatre st-denis',
    'mtelus',
    'centre bell',
    'centre videotron',
    'place bell',
    'opera de montreal',
    'orchestre symphonique',
    'osm',
    'francofolies',
    'festival de jazz',
    'grand prix',
    'cf montreal',
    'canadiens',
    'alouettes',
    'rocket de laval',
    'remparts',
    'biodome',
    'planetarium',
    'insectarium',
    'centre des sciences',
    'pointe-a-calliere',
    'musee des beaux-arts',
    'valcartier',
    'village vacances',
    'super aqua club',
    'zoo de granby',
    'parc omega',
    'laser tag',
    'trampoline park',
    'isaute',
    'clip n climb',
    'minigolf',
    'mini-golf',
    'karting',
    'go kart',
    'salle de spectacle',
    'boite a chanson',
    'discotheque',
    'club de nuit',
    'billetterie',
    'lepointdevente',
    'tickets',
    'billetterie evenko',
    'billetterie admission',
    'reseau admission',
    'salle de spectacle locale',
    'centre culturel',
    'maison de la culture',
    'salle communautaire spectacle',
    'salle de spectacle independante',
    'theatre communautaire',
    'cinema repertoire',
    'cinema independant',
    'salle imax scientifique',
    'centre d interpretation',
    'billetterie place des arts en ligne',
    'billetterie theatre du rideau vert',
    'billetterie tohu',
    'spectacle de cirque du soleil',
  ],
  lecture: [
    'livres et lecture',
    'renaud-bray',
    'renaud bray',
    'archambault',
    'indigo',
    'chapters',
    'librairie',
    'livre',
    'bouquin',
    'kindle',
    'kobo',
    'audible',
    'bibliotheque',
    'magazine',
    'le devoir',
    'journal',
    'abonnement magazine',
    'la presse',
    'librairie monet',
    'librairie gallimard',
    'librairie raffin',
    'raffin',
    'buropro',
    'coles',
    'les libraires',
    'leslibraires',
    'bande dessinee',
    'presse plus',
    'l actualite',
    'protegez-vous',
    'national geographic',
    'the gazette',
    'le soleil',
    'le droit',
    'journal de montreal',
    'journal de quebec',
    'abonnement journal',
    'librairie d occasion',
    'livres usages',
    'papeterie',
    'book',
    'bookstore',
    'library',
    'librairie independante',
    'librairie pantoute',
    'librairie de quebec',
    'boutique bd',
    'librairie jeunesse',
    'librairie du square',
    'librairie michel fortin',
    'librairie boyer',
    'kiosque a journaux',
  ],
  // Sans « avis », mot courant d'un recu avant d'etre un loueur de voitures.
  voyages: [
    'voyages',
    'air canada',
    'air transat',
    'transat',
    'sunwing',
    'porter',
    'westjet',
    'flair',
    'expedia',
    'booking',
    'airbnb',
    'hotel',
    'motel',
    'auberge',
    'billet d avion',
    'croisiere',
    'agence de voyage',
    'aeroport',
    'passeport',
    'enterprise',
    'hertz',
    'location de voiture',
    'greyhound',
    'auberge de jeunesse',
    'location de chalet',
    'flixbus',
    'camping',
    'parc national',
    'sepaq',
    'hotels com',
    'trivago',
    'kayak',
    'vrbo',
    'marriott',
    'hilton',
    'holiday inn',
    'best western',
    'fairmont',
    'sheraton',
    'delta hotels',
    'comfort inn',
    'super 8',
    'travelodge',
    'quality inn',
    'hampton inn',
    'chateau frontenac',
    'gite',
    'pourvoirie',
    'air france',
    'klm',
    'lufthansa',
    'british airways',
    'united airlines',
    'american airlines',
    'jetblue',
    'southwest',
    'copa',
    'aeromexico',
    'swoop',
    'lynx air',
    'vacances air canada',
    'club med',
    'vacances transat',
    'aeroplan',
    'duty free',
    'boutique hors taxes',
    'voyages en groupe',
    'circuit touristique',
    'excursion',
    'visite guidee',
    'sepaq reservation',
    'camping quebec',
    'koa',
    'terrain de camping',
    'chalet a louer',
    'resort',
    'all inclusive',
    'tout inclus',
    'hostel',
    'travel',
    'airlines',
    'flight',
    'agence voyages transat',
    'club voyages',
    'voyages carlson wagonlit',
    'boutique de voyage',
    'sunquest',
    'nolitours',
    'agence en ligne voyage',
    'voyage organise',
    'agence de voyages locale',
    'voyages en groupe organise',
    'tour operateur',
    'croisieres holland america',
    'croisieres royal caribbean',
    'croisieres carnival',
    'excursion guidee locale',
    'circuit en autocar',
    'sejour tout inclus mexique',
    'sejour tout inclus cuba',
    'sejour tout inclus republique dominicaine',
    'voyages selectour',
    'voyages laurier du vallon',
    'transat decouvertes',
    'itravel2000',
    'flightcentre',
    'flight centre',
  ],

  // famille
  'garde-enfants': [
    'garderie',
    'cpe',
    'service de garde',
    'gardienne',
    'nounou',
    'camp de jour',
    'camp d ete',
    'halte-garderie',
    'halte garderie',
    'educatrice',
    'agence de gardiennage',
    'garderie educative',
    'milieu familial',
    'garderie privee',
    'service de garde scolaire',
    'camp musical',
    'camp de vacances',
    'camp specialise',
    'babysitter',
    'gardiennage',
    'cpe subventionne',
    'frais de garde journalier',
    'maternelle privee',
    'prematernelle',
    'daycare',
    'centre de la petite enfance',
    'reseau de garderies',
    'garderie en milieu familial subventionnee',
    'programme de halte-garderie',
    'service de garde en milieu scolaire',
    'reseau des cpe du quebec',
    'agence de reference de gardiennes',
  ],
  animaux: [
    'animaux',
    'veterinaire',
    'animalerie',
    'mondou',
    'chico',
    'toilettage',
    'chien',
    'litiere',
    'croquettes',
    'nourriture pour chien',
    'pension pour animaux',
    'clinique veterinaire',
    'refuge animalier',
    'pattes et griffes',
    'pmc',
    'animal expert',
    'rens pets',
    'ren s pets',
    'petsmart',
    'pet smart',
    'petland',
    'global pet foods',
    'hopital veterinaire',
    'clinique animale',
    'spca',
    'sos animaux',
    'pension canine',
    'dressage canin',
    'garderie canine',
    'educateur canin',
    'toiletteur',
    'royal canin',
    'purina',
    'hills',
    'boutique pour animaux',
    'aquariophilie',
    'animalerie du coin',
    'chat',
    'chien et chat',
    'pet',
    'vet clinic',
    'clinique veterinaire urgence',
    'hopital veterinaire animaux',
    'boutique animalerie en ligne',
    'reseau veterinaire',
    'clinique veterinaire mobile',
    'boutique animalerie mondou reseau',
    'clinique veterinaire dmv',
  ],
  // Sans « emballage » : des frais d'emballage ne font pas un cadeau. Sans « faire-part »,
  // article de papeterie autant que cadeau.
  'cadeaux-offerts': [
    'cadeaux offerts',
    'carte-cadeau',
    'carte cadeau',
    'anniversaire',
    'noel',
    'mariage',
    'bapteme',
    'baby shower',
    'fete des meres',
    'fete des peres',
    'fleuriste',
    'bouquet de fleurs',
    'livraison de fleurs',
    'ballons',
    'party expert',
    'articles de fete',
    'boutique cadeau',
    'cadeau souvenir',
    'panier cadeau',
    'gravure',
    'personnalisation',
    'shower',
    'liste de mariage',
    'gift',
    'gift card',
    'boutique cadeaux uniques',
    'magasin de cadeaux',
    'cadeau personnalise en ligne',
    'boutique artisanale cadeaux',
    'boutique de cadeaux artisan quebecois',
  ],
  // Sans « sainte-justine » seul : un nom de rue et d'hopital, pas un don.
  dons: [
    'dons de charite',
    'centraide',
    'croix-rouge',
    'croix rouge',
    'unicef',
    'oxfam',
    'medecins sans frontieres',
    'fondation',
    'leucan',
    'moisson montreal',
    'guignolee',
    'eglise',
    'don mensuel',
    'telethon',
    'operation nez rouge',
    'banque alimentaire',
    'societe canadienne du cancer',
    'fondation du cancer',
    'chu sainte-justine',
    'shriners',
    'armee du salut',
    'jeunesse au soleil',
    'sun youth',
    'dystrophie musculaire',
    'coeur et avc',
    'diabete quebec',
    'wwf',
    'greenpeace',
    'amnistie internationale',
    'vision mondiale',
    'operation enfant soleil',
    'arbre de l espoir',
    'dons planifies',
    'campagne de financement',
    'collecte de fonds',
    'charite',
    'organisme de bienfaisance',
    'donation',
    'charity',
    'don en ligne',
    'campagne caritative',
    'fondation locale',
    'organisme communautaire don',
    'fondation du grand montreal',
    'fondation de l hopital sainte-justine',
    'clinique communautaire don',
  ],

  // education
  // Sans « edouard-montpetit » ni « lionel-groulx » seuls : des rues et des stations de metro
  // avant d'etre des colleges, que « cegep » et « college » nomment deja.
  scolarite: [
    'scolarite',
    'universite',
    'cegep',
    'college',
    'uqam',
    'udem',
    'mcgill',
    'concordia',
    'ulaval',
    'hec montreal',
    'polytechnique',
    'frais de scolarite',
    'droits de scolarite',
    'inscription scolaire',
    'ecole privee',
    'materiel scolaire',
    'residence etudiante',
    'frais afferents',
    'rentree scolaire',
    'fournitures scolaires',
    'universite laval',
    'uqtr',
    'uqac',
    'uqar',
    'uqo',
    'uqat',
    'ecole de technologie superieure',
    'enap',
    'teluq',
    'universite de sherbrooke',
    'bishop',
    'dawson',
    'vanier',
    'john abbott',
    'college ahuntsic',
    'college de maisonneuve',
    'college rosemont',
    'college montmorency',
    'cegep garneau',
    'cegep limoilou',
    'cegep sainte-foy',
    'commission scolaire',
    'centre de services scolaire',
    'csdm',
    'cssdm',
    'ecole secondaire',
    'ecole primaire',
    'college prive',
    'brebeuf',
    'regina assumpta',
    'frais d inscription scolaire',
    'surveillance des midis',
    'sortie educative',
    'album des finissants',
    'uniforme scolaire',
    'tuition',
    'school',
    'ecole internationale',
    'programme educatif prive',
    'ecole alternative',
    'institut d enseignement prive',
  ],
  // Sans « cours » ni « atelier » : trop courants, et un atelier est aussi un garage.
  formation: [
    'formation',
    'udemy',
    'coursera',
    'linkedin learning',
    'masterclass',
    'formation en ligne',
    'certification',
    'seminaire',
    'webinaire',
    'duolingo',
    'skillshare',
    'pluralsight',
    'edx',
    'khan academy',
    'ecole de conduite',
    'tecnic',
    'ecole de langues',
    'alliance francaise',
    'berlitz',
    'bootcamp',
    'le wagon',
    'brainstation',
    'datacamp',
    'codecademy',
    'oreilly',
    'o reilly',
    'pmi',
    'certification pmp',
    'asp construction',
    'carte aces',
    'cours de secourisme',
    'rcr',
    'ambulance saint-jean',
    'cours de conduite',
    'permis probatoire',
    'cours prive',
    'tutorat',
    'professeur particulier',
    'cours de musique',
    'ecole de musique',
    'conservatoire',
    'cours de danse',
    'cours de langue',
    'training',
    'workshop',
    'centre de formation professionnelle',
    'formation continue',
    'reseau de formation en ligne',
    'institut de formation',
    'reseau de formation continue quebec',
    'reseau de cegeps formation continue',
    'institut de technologie formation',
  ],

  // finances
  // Un virement vers l'epargne ne se photographie pas non plus.
  epargne: [],
  // Un remboursement de dette est une ligne de releve, jamais une photo de recu. Ses
  // mots-cles de marque (« visa », « mastercard ») se declencheraient de surcroit sur le
  // pied de ticket de presque tous les terminaux.
  'remboursement-dette': [],
  // Sans les noms d'institutions : ils s'impriment dans le pied de ticket du terminal
  // (« DESJARDINS » sur un releve Interac) sans que le commerce soit une banque. Seuls les
  // libelles de frais restent. « guichet » seul est trop commun.
  'frais-bancaires': [
    'frais bancaires',
    'frais mensuels',
    'frais de service',
    'frais de guichet',
    'frais nsf',
    'frais de retard',
    'frais d interet',
    'frais annuel',
    'frais de change',
    'frais de conversion',
    'frais de decouvert',
    'frais de virement',
    'frais interac',
    'frais de guichet automatique',
    'frais d administration',
    'frais de tenue de compte',
    'frais de cheque',
    'frais de transfert',
    'frais de plan',
    'cotisation annuelle carte',
    'frais de dossier bancaire',
    'frais de compte',
    'frais de service mensuel',
    'frais d utilisation guichet',
    'frais de compte affaires',
    'frais de service bancaire mensuel commerce',
  ],
  impots: [
    'impots',
    'revenu quebec',
    'revenu canada',
    'agence du revenu',
    'cra',
    'impot federal',
    'impot provincial',
    'acomptes provisionnels',
    'taxes municipales',
    'taxe scolaire',
    'taxe de bienvenue',
    'solde d impot',
    'impot foncier',
    'declaration de revenus',
    'taxe fonciere',
    'taxes municipales annuelles',
    'mrc',
    'h&r block',
    'impotrapide',
    'turbo impot',
    'turboimpot',
    'ufile',
    'rapport d impot',
    'cotisation rrq',
    'cotisation rqap',
    'assurance emploi',
    'acompte provisionnel',
    'avis de cotisation',
    'remise de taxes',
    'tps tvq a remettre',
    'impot sur le revenu',
    'declaration fiscale',
    'centre fiscal',
    'bureau des services fiscaux',
    'preparation de declaration',
    'service de comptabilite fiscale',
    'cabinet comptable impots',
  ],

  // divers
  'autre-depense': [
    'dollarama',
    'amazon',
    'temu',
    'aliexpress',
    'ebay',
    'etsy',
    'best buy',
    'la source',
    'apple store',
    'bureau en gros',
    'staples',
    'paypal',
    'kijiji',
    'marketplace',
    'wish',
    'dollar tree',
    'magasin a un dollar',
    'giant tiger',
    'rossy',
    'hart',
    'postes canada',
    'poste canada',
    'purolator',
    'fedex',
    'ups',
    'dhl',
    'point de depot',
    'toys r us',
    'toysrus',
    'benjo',
    'l imaginaire',
    'club jouet',
    'jouets',
    'lego',
    'michaels',
    'deserres',
    'omer deserres',
    'club tissus',
    'fabricville',
    'vitrine sur l art',
    'photo service',
    'imprimerie',
    'vistaprint',
    'serrurier mobile',
    'consigne bouteilles',
    'friperie en ligne',
    'vente de garage',
    'marche aux puces',
    'boutique en ligne',
    'frais de douane',
    'frais d expedition',
    'livraison colis',
    'plateforme de vente en ligne',
    'marche en ligne',
    'boutique generale',
    'magasin a grande surface',
    'grande surface',
    'service de reparation general',
    'boutique specialisee en ligne',
    'service de location d equipement',
    'atelier de reparation general',
    'magasin de surplus',
    'boutique d occasion generale',
    'boutique de surplus d entrepot',
    'service de nettoyage a sec',
    'boutique de reparation d electronique',
    'atelier de reparation de velo boutique',
  ],
}
